### ISSUE TITLE
Unable to assign issue

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-Hive/access-hive.github.io#119]
How to contribute says

After creation, please [assign the Issue to yourself in the right-hand side panel](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) if you intend on working on the issue.

I tried this after creating #118, but I only have a list, not a menu, on the RHS. The github documentation says "Anyone with write access to a repository can assign issues and pull requests." but it seems to mean only those with write access can assign even to themselves.

**Comment by ccarouge** [comment]
OK, we'll have to see what we do about the permissions on this repo. Assignation of the issue isn't a big deal, especially once there is a PR open and linked. So I could just remove that from the contribution guidelines for now. Would that be OK?

**Comment by MartinDix** [comment]
Ok with me.
