### ISSUE TITLE
Feedback to Soft Launch

### ISSUE THREAD

**Issue by NBateman-bit** [ACCESS-Hive/access-hive.github.io#127]
I love the feeling of the site and that is clean and very clear.

I feel the tabs ACCESS Hive and About should be merged  to just About, and perhaps would be good to have a tab called Contributions or How to contribute?. About could have the general description, links to the ACCESS-NRI website, etc, the tip square and License info

A question for the ACCESS-Hive tab. It says: “This portal goal is primarily to link to documentations hosted on other sites. It is not intended to host the documentation itself”, where then is the ACCESS-NRI supported documentation going to go? (you probably already explaining to me but I have forgotten) and should we explain that here?

In the Components tab, as I was mentioning before, I would change the icons to the ones that include their name on the design.

I think we should discuss the Events page: I think it would be great if the community adds events there, but should we have (as we were discussing another one on the external website? – it could be that I make sure the ones that the community add in the ACCESS-Hive are also in the other one, or, that we have only the one in the ACCESS-Hive…

**Comment by ccarouge** [comment]
Closing this as I think we have addressed or are addressing the feedback through various issues.
