### ISSUE TITLE
Forum setup and linking

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#130]
We need a forum for community interaction, support and self-organisation. This needs to interact well with the hive.

List of requirements for forum

- [x] User sign-up options
- [ ] Who are moderators?
- [ ] Link to code of conduct
- [ ] Meta information about the forum, what it is for and how it is organised
- [x] Check mailing list capability with locked topic

Requirements for linking from Hive

- [ ] Add link to forum

**Comment by aidanheerdegen** [comment]
Added GitHub and Google sign-up options. It is [possible to add OrcID authentication](https://meta.discourse.org/t/sign-in-to-discourse-using-orcid/105488/2) but for a hosted solution that [requires a business plan](https://www.discourse.org/plugins/oauth.html).

**Comment by aidanheerdegen** [comment]
Need a guinea pig user without admin privileges to test the functionality of using closed forum topics as targeted mailing lists.

@dougiesquire could you sign up to https://access.discourse.group (if you're happy to do so, can you sign in with your GitHub account to test that it works)

Then cruise over to this topic:

https://access.discourse.group/t/notifications-about-something-important/13/7

and down the bottom select the notifications status to "Watching". Let me know when you do this and I'll try posting some stuff there, and see if you get notifications of what I post.

**Comment by dougiesquire** [comment]
Trying to log in with Github returned a 404 error. I'll wait to progress further so I can test any changes you make

**Comment by aidanheerdegen** [comment]
Hi @dougiesquire. I've configured it correctly, can you try again? Thanks.

**Comment by dougiesquire** [comment]
Ta - I'm now successfully logged in (via Github) and watching the above topic

**Comment by dougiesquire** [comment]
@aidanheerdegen,

- yes, I got an email notification about your post
- there's no option to reply to the thread on discourse. The email notification suggests that I can reply to the email to reply to the thread, but that returned a reply saying "The topic you are replying to is currently closed and no longer accepting replies" and giving me an option to contact admin

**Comment by aidanheerdegen** [comment]
Thanks @dougiesquire! Much appreciated. This gives people a method to create targeting mailing lists for specific topics, that won't get spammed by people who don't realise they shouldn't reply to them.
