### ISSUE TITLE
Review of "how to contribute" guide

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-Hive/access-hive.github.io#133]
With the changes made to the organisation and the About section, some changes are necessary for the "how to contribute" guide.

- Navigation: Should the guide still be in one page? Could we put it as a sub-section of the About tab with several sub-pages? Would it feel less dense and easier to navigate?
   - New possible structure of guidelines:
       - Abstract
       - Quick change from GitHub
       - Working on your local computer
       - How to share documentation that isn't published online
       - Understand the navigation.

- Content changes: 
   - remove the text about assigning issues
   - explain the local modifications can create a fork (non-organisation members) or a branch (organisation members)
   - explain what to do with orphaned documentation

**Comment by ccarouge** [comment]
For orphaned documentation, list options (Zenodo, repository in ACCESS-Collective).
