### ISSUE TITLE
 "MED": review content of the splash screen 

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-Hive/access-hive.github.io#134]
- [x] Define ‘MED’ acronym at start of description if it’ll be used
- [x] Though again, I’d consider keeping it general as ‘ACCESS-NRI will offer’ as it might be cleaner (mainly because we don’t have a clear public description of our org though I also think it helps keep it broad and inclusive for the community and other teams)
If going with this approach, the line ‘MED Team will offer:” could be rephrased to something ‘coming soon’ etc.
- [ ] Under the ‘MED team will offer’ section, think we should rephrase a few of the dot points… need to have quick think and will add some suggestions (it’s mainly to avoid confusion or the grey area between what we can access or what is information we provide about access)

**Comment by ccarouge** [comment]
I'd say this was done? Can you confirm please?

**Comment by rbeucher** [comment]
No it wasn't @kdruken wanted to go through it.

**Comment by kdruken** [comment]
Leaving this with @rbeucher to decide if he'd like to keep as is or rephrase slightly (he had good suggestion to use as opportunity to direct people to forum to add feedback/discuss across these topics). Will leave with him.

**Comment by rbeucher** [comment]
I am closing this.
