### ISSUE TITLE
Indexing the Hive into Google and other search engines

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-Hive/access-hive.github.io#137]

**Comment by rbeucher** [comment]
Indexing of the https://access-hive.github.io/ACCESS-Hive URL is in the Google queue...

We can check on Google Search Console using the ACCESS Bot google account
https://search.google.com/search-console/about

**Comment by aidanheerdegen** [comment]
I can see access-hive.org.au in google but not forum.access-hive.org.au yet.

**Comment by rbeucher** [comment]
I have not requested indexing of the forum.

**Comment by aidanheerdegen** [comment]
Looks like forum.access-hive.org.au is now being indexed. Will close this issue.
