### ISSUE TITLE
Code of conduct, ethics and acknowledgement of country

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#146]
Spawned from #70 and #138

Grouped as these require collaboration with Natalia

- [x] Acknowledgement of country? (https://github.com/ACCESS-Hive/ACCESS-Hive/issues/72)
- [x] Code of conduct / ethics statement? (https://github.com/ACCESS-Hive/ACCESS-Hive/issues/72)

**Comment by rbeucher** [comment]
The github community guidelines are quite good.

https://docs.github.com/en/site-policy/github-terms/github-community-guidelines

**Comment by aidanheerdegen** [comment]
This is a nice example of a code of conduct

https://github.com/Spatialised/gdal-tiler/blob/master/CODE_OF_CONDUCT.md

**Comment by aidanheerdegen** [comment]
There is now this banner on the website

> We at ACCESS-NRI acknowledge the Traditional Owners of the land on which our research infrastructure and community operate across Australia and pay our respects to Elders past and present. We recognise the thousands of years of accumulated knowledge and deep connection they have with all the Earth systems we simulate.

So I guess we'll just have to reproduce that?

**Comment by rbeucher** [comment]
Yes I think so.

**Comment by ccarouge** [comment]
There is now a code of conduct on the ACCESS-NRI website we can refer to from the Hive: https://www.access-nri.org.au/community/access-nri-code-of-conduct/

**Comment by rbeucher** [comment]
OK Where does that go?

**Comment by aidanheerdegen** [comment]
Sub-section of About. I can do it.
