### ISSUE TITLE
Protect `gh_pages` branch

### ISSUE THREAD

**Issue by ccarouge** [ACCESS-Hive/access-hive.github.io#148]
We want to protect the `gh_pages` branch so nobody can mistakenly break the published site. 

But simply adding an obligation of pull request breaks the CI as the JamesIves action pushes directly to the branch.

**Comment by ccarouge** [comment]
A solution is found [here](https://github.com/community/community/discussions/13836):

> You can create a "service user", add that service user to the "Restrict who can push to matching branches" list, create a Personal Access Token (PAT) for that service user, store the PAT in an environment secret, assign the relevant environment to your protected branch, and then have the workflow get the PAT from the environment, and then set up extra rules in all of your workflows triggerd by push events to make sure that they ignore any commits pushed by the service user (the way they'd ignore commits pushed using GITHUB_TOKEN). This more-or-less works, but it's a lot of work to replicate this set up across dozens of repositories, and it's really abusing a bunch of unrelated functionality for something that should be available out of the box.

@rbeucher @aidanheerdegen Do we have a better idea? Is the downside of the solution above acceptable?

**Comment by aidanheerdegen** [comment]
We only need to deploy this to one repo, so it is do-able. I agree it would be better is the GitHub Actions bot could be selected as an app that can push directly to a branch.

**Comment by ccarouge** [comment]
We need this on all the documentation repositories we will create in ACCESS-NRI. Or am I wrong here?

**Comment by aidanheerdegen** [comment]
Only team members will have access to them, so I think we don't need it for ACCESS-NRI repos.

**Comment by rbeucher** [comment]
So the @access-bot account could be use for this.
I have created a PAT and added a gh-pages environment with it. I can retrieve the PAT from the publish workflow and pass it to the JamesIves action... If we restrain access to gh-pages to @access-bot only this should work.
Pb is the PR-deploy workflow. I don't know how to get it to work...

**Comment by KAUR1984** [comment]
Closing as old issue.
