### ISSUE TITLE
Preview action is broken

### ISSUE THREAD

**Issue by ccarouge** [ACCESS-Hive/access-hive.github.io#163]
The preview action returns the wrong URL for the preview now that the repository name includes `.github.io`. The URL should simply be `https://<repo>` but it is given as `https://<org>.github.io/<repo>`

This has been solved in [v1.2.0 of rossjrw action](https://github.com/rossjrw/pr-preview-action/releases/tag/v1.2.0). But that version does not allow to build preview from forks. So to fix the problem for us, we need to update [our fork action](https://github.com/ACCESS-NRI/pr-preview-action).

**Comment by aidanheerdegen** [comment]
Didn't fix. Have updated out version of the preview plugin. Update to this (v2.1)

https://github.com/ACCESS-NRI/pr-preview-action/pull/4
