### ISSUE TITLE
Change Domain name on HIve Repo.

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-Hive/access-hive.github.io#169]
See

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#co[…]ain

Note that this is an “Apex domain” which is a bit more complex than configuring a straight subdomain, and requires setting up an ALIAS  or A DNS record.

**Comment by rbeucher** [comment]
Also see this about correct placement of the CNAME file in the repo
https://www.mkdocs.org/user-guide/deploying-your-docs/#custom-domains

**Comment by aidanheerdegen** [comment]
Closed by https://github.com/ACCESS-Hive/access-hive.github.io/pull/172

**Comment by aidanheerdegen** [comment]
Checking Github trackback links: see https://forum.access-hive.org.au/t/custom-domain-name/24

**Comment by aidanheerdegen** [comment]
Checking Github trackback links: see https://forum.access-hive.org.au/t/custom-domain-name/24
