### ISSUE TITLE
Become a member of the ACCESS-Hive repository

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#179]
If you want to become a member of this repository reply to this issue and ping the @ACCESS-Hive/maintainers team to request an invitation to join.

**Comment by ccarouge** [comment]
@ACCESS-Hive/maintainers Is that necessary knowing each team has a discussion page? Is that discussion page public or not? https://github.com/orgs/ACCESS-Hive/teams/maintainers

**Comment by rbeucher** [comment]
I don't think it is public...

**Comment by rbeucher** [comment]
Pb with the issue is it could actually be too much public...

**Comment by navidcy** [comment]
I'm replying. :)

**Comment by aidanheerdegen** [comment]
> I'm replying. :)

I have sent an invitation @navidcy. I've made you a reviewer to begin with. We don't have a policy about who is part of the editors group, which can make repos and merge PRs. If you need to do that we can add you to the Editors group.

ACCESS-Hive is a **portal** to find documentation, not host it, though it is possible to create another repository under the ACCESS-Hive organisation for some stand-alone documentation and link to it from ACCESS-Hive.

ACCESS-Hive really needs community involvement, add links to existing community documentation, or modify/update what is already there.

Also any feedback about usability is very welcome.

**Comment by lidefi87** [comment]
I would like to become a contributor. I will likely be making some contributions to the documented examples soon. I am also happy to help testing some of the notebooks already published to make sure they are still working.

**Comment by aidanheerdegen** [comment]
Hi Denisse (@lidefi87). I have invited you to become a member of ACCESS-Hive. Welcome!

Note that the main ACCESS-Hive website is simply a portal to existing documentation. This is important, because the community needs to access documentation now, but ACCESS-NRI doesn't have the resources to be able to take all existing documentation and re-publish it, and in many cases it couldn't, for licensing or other reasons. 

So ACCESS-Hive was set up to make it easy to find what already exists, and as a source of information for ACCESS-NRI staff to consult when we do create the documentation necessary to support our releases.

If you have specific notebooks you're keen to use/test/document or improve can you provide a link to them? I know @rbeucher is keen to know what is already out there, what the community would like to see supported etc, and how we can collaborate. If you have a wider discussion in mind about existing documentation and examples the [ACCESS-Hive Forum ](https://forum.access-hive.org.au)would be a great place to talk about it, and involve colleagues.

**Comment by lidefi87** [comment]
Hi @aidanheerdegen, I just accepted the invitation. My focus is on using outputs for ecological questions, so I would like to contribute some examples that would help other ecologists assess whether ACCESS would be a suitable for their research. But, I am also happy to contribute to make it easier for others, especially less experienced users, to access outputs and learn the basics of data manipulation.

**Comment by aidanheerdegen** [comment]
Hi Denisse (@lidefi87). Sounds like these should be included in the COSIMA Recipes, is that right? Perhaps this forum discussion would be a good place to suggest this and figure out a process for getting your examples included.

https://forum.access-hive.org.au/t/how-can-we-get-new-cosima-recipes/119

**Comment by navidcy** [comment]
@lidefi87 has been invited as a cosima-recipes collaborator :)

**Comment by lidefi87** [comment]
Amazing! I have accepted your invitation @navidcy

**Comment by NBateman-bit** [comment]
I would like to be added please.

**Comment by ccarouge** [comment]
Invitation sent to @NBateman-bit by @aidanheerdegen

**Comment by aidanheerdegen** [comment]
Sorry, I should have said I had done this. Will try and remember to do so next time.
