### ISSUE TITLE
Add xmovie link

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#182]
Worth to link to xmovie? Seems a very cleanly executed, if not extensive, package. Written by someone who is quite involved in pangeo I believe.

https://xmovie.readthedocs.io/en/latest/examples/quickstart.html

**Comment by aidanheerdegen** [comment]
Testing linkbacks to forum https://forum.access-hive.org.au/t/this-is-a-test-topic/48/2

**Comment by aidanheerdegen** [comment]
See #207, but this should be added to a relevant index of tools rather than linked directly in the ACCESS-Hive.

**Comment by navidcy** [comment]
Definitely worths putting a link.
I'd suggest link to the stable version of the docs --> https://xmovie.readthedocs.io/en/stable/examples/quickstart.html

**Comment by aidanheerdegen** [comment]
What I'm suggesting is to add it to an index of packages like https://pyaos.github.io/packages/

**Comment by navidcy** [comment]
Yes. And those packages perhaps be installed in the conda-analysis env?

Who is maintaining the conda-analysis envs? ACCESS-NRI? CMS? Other?

**Comment by aidanheerdegen** [comment]
CMS. You can make an issue in the repo to add packages

https://github.com/coecms/conda-envs/issues

**Comment by aidanheerdegen** [comment]
Added to PyAOS catalogue.
