### ISSUE TITLE
Remove data products section

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#185]
Add "what are reanalyses" to the splash screen at 

https://access-hive.org.au/model_evaluation/datasets/#jra55-do

**Comment by paolap** [comment]
What are your long term plans with this section? I was wondering when I found it yesterday, as we are working on a portal to have all the data in one place, we could even create a ACCESS-NRI community to list only what's relevant to you, but just re-listing data in your hive seems like a lot of work and yet again another source for users.
A link tot he portal:
https://oneclimate.dmponline.cloud.edu.au

The NESP2 community as an example:
https://oneclimate.dmponline.cloud.edu.au/communities/nesp-input?q=&l=list&p=1&s=10&sort=newest

**Comment by aidanheerdegen** [comment]
Good point. I don't think we have long term plans. The only reason I put those there was I wanted to reference them from the ACCESS-OM section

https://access-hive.org.au/configurations/access-om/

Probably makes sense to not do that. Also makes sense to limit cross-linking in ACCESS-Hive itself, as that is a maintenance nightmare. 

So I'll delete that section and remove the internal links.
