### ISSUE TITLE
Link to `maintainers` in How to contribute guide is broken

### ISSUE THREAD

**Issue by lidefi87** [ACCESS-Hive/access-hive.github.io#187]
This is the website I'm referring to https://access-hive.org.au/about/contribute/ under the "Become a member of the ACCESS-Hive organisation" section

**Comment by aidanheerdegen** [comment]
Hi Denisse,

Thanks for pointing that out. The link only works for members of the organisation, so is effectively broken for anyone who wishes to join.

I have replaced with a link to an issue where you can request to join the organisation

https://github.com/ACCESS-Hive/access-hive.github.io/issues/179

If you would like to join could you try requesting on that issue, as it gives others an idea that it actually works! 

Cheers

**Comment by lidefi87** [comment]
That is great! I will be replying to the other issue shortly. Thanks!
