### ISSUE TITLE
Link to ACCESS-CM2 and ESM1.5 training/documentation

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-Hive/access-hive.github.io#195]
There is some material at https://confluence.csiro.au/display/ACCESS/ACCESS+Training

Also COE CMS documentation at http://climate-cms.wikis.unsw.edu.au/ACCESS

**Comment by dougiesquire** [comment]
Also this for ESM if not already included in the above links:
https://github.com/coecms/esm-lig

**Comment by ccarouge** [comment]
@dougiesquire the GitHub repository is only one of several: one such repository per configuration ported to `payu`. All of them are discoverable from the CMS wiki ACCESS page given by Martin. But we probably want to make things easier for people and put http://climate-cms.wikis.unsw.edu.au/ACCESS-ESM_1.5 under ACCESS-ESM. This page has links to the GitHub repositories for all the configurations ported.
