### ISSUE TITLE
Australian Community Reference Climate Data Collection @ NCI

### ISSUE THREAD

**Issue by paolap** [ACCESS-Hive/access-hive.github.io#199]
Thank you for sharing a resource with the ACCESS community

If there is a new resource you would like to add to the ACCESS-Hive please include the following information:

Link:
https://aus-ref-clim-data-nci.github.io/aus-ref-clim-data-nci/intro.html

Description:
A collaboration between the Australian Climate Service (ACS), ARC Centre of Excellence for Climate Extremes (CLEX) and the wider Australian climate research community to re-establish and maintain a reference dataset collection at NCI.
An [intake-esm catalogue](https://github.com/aus-ref-clim-data-nci/acs-replica-intake) is also available to facilitate data access.

Category
Model evaluation and data
Data catalogs

I would be happy to contribute the change myself if you are interested.

**Comment by aidanheerdegen** [comment]
Sounds great, thanks! I've assigned it to you, but feel free to self-assign in the future if you have time to do the changes yourself.

**Comment by aidanheerdegen** [comment]
@heidinett If you wanted to you could assign this to yourself and add it to the hive.

**Comment by paolap** [comment]
completely forgot about this, sorry

**Comment by heidinett** [comment]
@paolap Would you like me to make a PR for this and tag you as a reviewer, or would you prefer to do this?

**Comment by paolap** [comment]
If you could do that would be great as I'm currently sick just trying to wrap up before the end of the year, if you need more information is available in the documentation (link provided) thanks

**Comment by heidinett** [comment]
No problem. I will take care of this.
