### ISSUE TITLE
What's supposed to go in MED/Data processing?

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-Hive/access-hive.github.io#202]
I'm confused about what the difference is between the content of the [MED/Data processing](https://access-hive.org.au/model_evaluation/data_processing/) page and the MED/component pages (e.g. [MED/Atmosphere](https://access-hive.org.au/model_evaluation/atmosphere/)). Both seem to document tools for data processing.

If an example is useful, where should a tool like [climpred](https://climpred.readthedocs.io/en/stable/) be documented? Should there be a climpred entry in each relevant component, or should it live in Data processing? Does it matter?

cc @rbeucher, @aidanheerdegen

**Comment by rbeucher** [comment]
I see your point and I agree it's confusing. I would put the link in both for now but we need a better way.
