### ISSUE TITLE
Links to collated indexes of tools?

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-Hive/access-hive.github.io#207]
There're a few existing collated lists of tools that are relevant/useful to the climate community. Should we link these and where?

- https://pyaos.github.io/packages/
- some things in here: https://docs.xarray.dev/en/stable/ecosystem.html
- A few of us in the ACDG are working on a ["working with big data" Jupyter book](https://github.com/ACDguide/BigData) that includes lists of useful tools. It's not quite ready for prime-time yet, but it isn't far away
- others, I'm sure

**Comment by dougiesquire** [comment]
Relevant to #182. Where would something like this live?

**Comment by aidanheerdegen** [comment]
Yeah I now think it is probably too low level to just link to a single package (like `xmovie`), and pointing to curated/collated indexes of tools makes more sense. So we should decide on an index to link to and contribute resources to it. I didn't realise pyaos was still going, I thought the folks working on it had joined in with pangeo. 

So is https://pyaos.github.io/ where we should be adding information? Would @DamienIrving welcome our contributions, or does he want that to be curated for a specific audience?

I reckon you should link to the big data Jupyter project, but mark as "work in progress". Might be a good way to get some more interest and maybe contributions?

**Comment by aidanheerdegen** [comment]
As for where to put the links, I guess https://access-hive.org.au/model_evaluation/data_processing/ 

Either in the Data Processing Tools section with it's own sub-heading, or making a new section "Tool catalogs" or similar? In which case maybe it makes sense for `xskillscore` to be listed in an index/catalog? Where to draw lines and organise stuff is fuzzy, so it is fine to iterate a bit to find a happy medium.

**Comment by dougiesquire** [comment]
Project Pythia is another great resource to link that's rapidly expanding: https://projectpythia.org/

**Comment by aidanheerdegen** [comment]
Project Pythia does look very good already, and as you say increasing rapidly. It has a [resources page](https://access-hive.org.au/model_evaluation/data_processing/) that looks to be slightly different in scope to the pyaos index. 

Project Pythia is something that is worthwhile linking to in ACCESS-Hive I think.

**Comment by DamienIrving** [comment]
I spoke with Project Pythia a while back about them hosting / taking over the maintenance of the PyAOS package index but they weren't interested. Like you say, the vision for their resource gallery is a little different than for the package index.

[This page](https://github.com/PyAOS/pyaos.github.io/blob/master/README.md#scope) explains the scope of the PyAOS package index - very happy to receive contributions that are consistent with that scope :smile:

**Comment by aidanheerdegen** [comment]
Thanks @DamienIrving. It isn't straightforward to define the scope of something (as we are discovering in real time!), so well done for doing so. 

Sounds like we should, in the first instance, encourage PRs to your PyAOS package index, with reference to the scope of the project. No doubt there will be some that aren't appropriate, and feel free to let us know.

As a first cab off the rank, do you imagine [xskillscore](https://github.com/xarray-contrib/xskillscore) would be appropriate? 

It would be nice to have some metrics to judge if something were appropriate. e.g. libraries.io has a "quality score" based on a bunch of stuff

https://libraries.io/conda/xskillscore

> I spoke with Project Pythia a while back about them hosting / taking over the maintenance of the PyAOS package index but they weren't interested (so I'm still very much actively maintaining it).

Is this something you need assistance with?

**Comment by DamienIrving** [comment]
xskillscore is a good suggestion - added :smile: https://github.com/PyAOS/pyaos.github.io/commit/9cda705d3eea18aa86aa2eb40921aefb819c4421

Incorporating some objective metrics into the decision making for which packages get included in the index is definitely worth thinking about - I've created an issue to start taking notes on the topic: https://github.com/PyAOS/pyaos.github.io/issues/7

Feel free to encourage PRs. I don't need assistance beyond that really - the most useful thing is having people alert me to libraries I'm not aware of.

**Comment by aidanheerdegen** [comment]
@heidinett added a "Resources" tab, so now I think there is an obvious place for the resources mentioned in the OP

https://github.com/ACCESS-Hive/access-hive.github.io/issues/207#issue-1444881108

If you wanted to add them @heidinett you can assign this to yourself and have a crack.

**Comment by aidanheerdegen** [comment]
Probably best to remove the link to `xskillscore` from the `Data Processing/Tools` as this is listed in `PyAOS` and we've decided to link to catalogues/lists of tools rather than try to put links to lots of individual packages on ACCESS-Hive.
