### ISSUE TITLE
Rename `ACCESS-Forum` to `ACCESS-Hive Forum`?

### ISSUE THREAD

**Issue by navidcy** [ACCESS-Hive/access-hive.github.io#210]
I know that it may be too long name? But already some people are a bit confused with "ACCESS-Hive" and "ACCESS-Hive Forum" so if you add another extra name "ACCESS-Forum" they might think it's a new thing... (I know I thought of that myself!)

https://github.com/ACCESS-Hive/access-hive.github.io/blob/e9394401e7e7f4219bb3983fb3ac8dbf12418915/overrides/partials/nav.html#L80

**Comment by navidcy** [comment]
I opened a PR. We can discuss here or there and decide if what I'm proposing is a good idea. I opened the PR mostly to be able to see how that would render.

**Comment by aidanheerdegen** [comment]
Hate to be a pain, but we should probably update the navigation tab which just says "Forum".

**Comment by rbeucher** [comment]
@navidcy is right. Should be ACCESS-Hive Forum.

Not sure about the tab...

**Comment by navidcy** [comment]
It just says "Forum" which is OK I feel.
It's the "ACCESS Forum" that I was pushing back.

It's in the menubar of ACCESS-Hive so it's quite obvious that it's the Hive's forum.

**Comment by ccarouge** [comment]
Agree with @navidcy: the tab can still say "Forum". @aidanheerdegen disagree or should we close this again?

**Comment by rbeucher** [comment]
Yep we close this again...;-)

**Comment by aidanheerdegen** [comment]
Sure.
