### ISSUE TITLE
How can users get support from ACCESS-NRI?

### ISSUE THREAD

**Issue by navidcy** [ACCESS-Hive/access-hive.github.io#215]
Should the ACCESS-Hive include some info on how simple users can get help?

This: https://access-hive.org.au/about/support/ just mentions to contact ACCESS-NRI directly.

Perhaps point users to the forum and urge them to search through there to see if what they are struggling with has been discussed before or open a new discussion if not?

**Comment by ccarouge** [comment]
The contact page needs some updates along the same lines as well: https://access-hive.org.au/about/contact/ 

The forum should be added. 

Actually, maybe the "support" page should link to the "contact" page which seems to have more information on how to get support than the "support" page does. 🙃

**Comment by aidanheerdegen** [comment]
I'll look into it.

**Comment by aidanheerdegen** [comment]
Contact is maybe different to support, but yeah point taken.

I think we should we remove slack, if we're planning on emphasising the forum as the best place to ask questions.
