### ISSUE TITLE
Clarify instructions to add events

### ISSUE THREAD

**Issue by ccarouge** [ACCESS-Hive/access-hive.github.io#225]
For newcomers to GitHub, it can be confusing to know what are all the steps needed when adding an event. 

The [Add event](https://access-hive.org.au/events/add_event/) page explains how to create the file but does not say where (in a branch) and does not explain the pull request process.

**Comment by ccarouge** [comment]
I have addressed some of this in #229 @aidanheerdegen but I'm probably doing something that is complementary to what you are looking into.

**Comment by aidanheerdegen** [comment]
Yeah I noticed. See #230
