### ISSUE TITLE
Markdown link check false positives

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#227]
The markdown-link check sometimes throws up false positives when a website doesn't respond quickly enough, or there is some temporary network issue or outage.

I propose we set `check-modified-files-only` to `yes` for PRs. That way contributors will not have to make decisions about dead links that are not to do with their PR.

In addition we should have a scheduled run that does a full link check, and perhaps use some of the more esoteric options, like `retryCount`, to make the check more robust

https://github.com/tcort/markdown-link-check#config-file-format

**Comment by ccarouge** [comment]
Would you do a full link check when merging a PR or only a scheduled run?

**Comment by aidanheerdegen** [comment]
Only a scheduled run I think. It isn't the responsibility of someone who submits a PR to figure out if other links are permanently down or not.

**Comment by ccarouge** [comment]
I agree with what you propose and no check when merging the PR.
