### ISSUE TITLE
Specify Reviewers team for review

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#231]
Currently when submitting a pull request we ask that contributors request a review by tagging the reviewers team. e.g. https://github.com/ACCESS-Hive/access-hive.github.io/pull/229#discussion_r1023503528 and in the review template.

It is possible to specifically request a team review a PR (it is inconsistent that this isn't possible when assigning an issue, hence there is some confusion about when this works). We should change advice to specifically ask contributors to request a review from the reviewers team.

**Comment by ccarouge** [comment]
Is the behaviour the same, ie. the whole team receives a notification about the pull request? Except the notification is a request for review and not a mention. Would that confuse some reviewers who would then think they need to review it instead of a choice of who picks it?

**Comment by aidanheerdegen** [comment]
Short story: it is configurable

https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team

**Comment by ccarouge** [comment]
We discussed this before. So what's preferable: 

- notify the whole team and let people self-assign
- use an algorithm from GitHub to choose for us

Am I complicating things for nothing? Should we just start with the default and move to using the GitHub algorithms if we see some issues?

**Comment by rbeucher** [comment]
I think we should start with the default. A round robin system would be good. People assigned can always re-assign to someone else if they think they are not a good fit...

**Comment by aidanheerdegen** [comment]
Ok, I've enabled auto-assignment, one reviewer and round-robin.

I will update the PR template instructions.

**Comment by aidanheerdegen** [comment]
After a couple of false starts, you are the lucky reviewer @rbeucher (honestly that is what GitHub chose)
