### ISSUE TITLE
[New Event]: Testing

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#232]
### Event title

Community Modelling Workshop

### Start date

30/10/2024

### End date

31/10/2024

### Location

Da Moon (virtual and online)

### Website

https://moon.nasa.gov

### Description

All and everything about the moon. You definitely want to be there.

**Comment by aidanheerdegen** [comment]
@ccarouge @rbeucher Whaddyareckon?

**Comment by rbeucher** [comment]
Do you want to use that as a template?

**Comment by aidanheerdegen** [comment]
That is the result from the form input, check it out yourself 

https://github.com/ACCESS-Hive/access-hive.github.io/issues/new?assignees=&labels=New+Event&template=new-event.yml&title=%5BNew+Event%5D%3A+

**Comment by aidanheerdegen** [comment]
It would be nice if the form could output yaml directly, but alas no. Or not that I could find.

**Comment by ccarouge** [comment]
It's fine for me.
