### ISSUE TITLE
Add link health badge

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#235]
Should add a badge with the status of the scheduled full link check test to the repo README. Maybe add to site too if that is considered useful.

**Comment by dougiesquire** [comment]
Is there an easy way to keep track of links that fail to flag links that have been failing for a while (without remembering/going through CI logs)?

**Comment by aidanheerdegen** [comment]
> links that fail to flag links that have been failing for a while

Je ne comprends pas

**Comment by aidanheerdegen** [comment]
I did wonder about automatically making an issue for failing links, but wanted to get a feeling for just how onerous that might be before doing it.
