### ISSUE TITLE
Maintaining citations easily and consistently

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#239]
It is possible to automatically generate BibTeX files from a DOI

https://chrisholdgraf.com/blog/2022/orcid-auto-update/

This would be an easier and more consistent method for maintaining citations: just add a DOI to a file and generate the `.bib` file using CI. The generation step has the potential to be a useful check that the citation is correct, or at least that the DOI resolves to something.

**Comment by rbeucher** [comment]
From my experience the DOI search functionality is not reliable. It often results in incomplete or plainly wrong citation.
I would stay away from automating this...

**Comment by aidanheerdegen** [comment]
Ok
