### ISSUE TITLE
[New Event]: UM/LFRic Partnership UM Partner Visiting Scientist Exchange Programme (UNITE)

### ISSUE THREAD

**Issue by NBateman-bit** [ACCESS-Hive/access-hive.github.io#245]
### Event title

UM/LFRic Partnership UM Partner Visiting Scientist Exchange Programme (UNITE)

### Start date

31/01/2023

### End date

31/01/20232

### Location

MetOffice, UK

### Website

http://www.metoffice.gov.uk 

### Description

The UM Partnership is happy to announce that is now accepting applications from scientists and software developers from across the UM Partnership and academic partners to the UM Partner Visiting Scientist Exchange Programme (UNITE). 
 
The UM Partner visiting scientist programme aims to encourage visiting scientist exchanges across multiple sites that would benefit the joint UM partner science programme and the technical infrastructure programmes. Visit topics should be prioritised and aligned with joint science and technical infrastructure programmes.  
 
Visits to and from UM Associates and academic partners engaged in UM partnership joint activities are in scope. Please note that visits focusing on staff development are out of scope and should be covered by the sponsoring organisation. 
 
Applications will be managed and prioritised by the UM Partnership Manager, in consultation with the relevant science or technical leads from coordination groups of the Joint Science Programme (e.g., RA and GC UM partner coordination groups) and the Technical Advisory Group (TAG). 
 
Please note that sufficient time should be planned to process the application, prepare for the visit, and consider lead times for visa processing. For example, the following should be considered:   
•	2 months minimum for a visit of a few days  
•	3 months minimum for visits longer than 2 weeks, or longer depending on visa requirements   
  
The funding can cover travel and accommodation for the duration of the proposed activity. Additional claims can be considered on a case-by-case basis. 
 
More information, including how to apply, please contact João Teixeira (he/him)
joao.teixeira@metoffice.gov.uk or if you have access go to the UM Partnership SharePoint site. If you would like to establish some collaborative work but are unsure of who might be best placed to work with you, please do not hesitate to contact [João Teixeira](mailto:joao.teixeira@metoffice.gov.uk). 
 
Please note the deadline for applications for this round is the 31 January. However, there are plans to run 6-monthly calls for the programme.

**Comment by NBateman-bit** [comment]
Hi @ACCESS-Hive/editors @aidanheerdegen  I just created this new event. It is note really training but a visiting fellowship, so not sure if it should go to events or in general?

**Comment by rbeucher** [comment]
Yes. Not sure what to do with this... It is not an event but could be relevant.
