### ISSUE TITLE
[New Resource]: Cylc and Rose forum

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#253]
There is a discourse forum for rose and Cylc and Rose

https://cylc.discourse.group

This is potentially a very useful source of information and help with all matters cylc and should be linked to from ACCESS-Hive.

This is probably best put in the new Resources > Tools category.

**Comment by aidanheerdegen** [comment]
I will add this, but is waiting on https://github.com/ACCESS-Hive/access-hive.github.io/issues/207 to be merged

**Comment by KAUR1984** [comment]
Closing as old issue. Could refer back in case for the update hive :)
