### ISSUE TITLE
Review categories and organisation

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#254]
Identified a need to review the top level categories and organisation of the site

https://github.com/ACCESS-Hive/access-hive.github.io/pull/252#issuecomment-1356903048

Precis: the organisation of the site is biased towards ACCESS-NRI activities and structure. Need to review in light of community users requirements.

**Comment by KAUR1984** [comment]
Closing as old issue.
