### ISSUE TITLE
[New Resource] Add COSIMA Cookbook Beginners Guide

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#258]
Add the [Beginner's Guide](https://github.com/COSIMA/cosima-cookbook/wiki/Beginners-Guide-to-the-COSIMA-Cookbook) to the [COSIMA Cookbook](https://access-hive.org.au/model_evaluation/ocean_seaice/#cosima-cookbook-recipes) entry.

**Comment by KAUR1984** [comment]
Closing as old issue, could refer back if we need to include it in the new hive. :)
