### ISSUE TITLE
Confusing UI on my phone

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-Hive/access-hive.github.io#260]
I'm possibly (probably) being dumb, but navigating to different pages (Configurations, Training etc) on the ACCESS Hive website feels a little unintuitive. After first arriving at the website, I have to click the menu icon and then click "<-" in the sidebar in order to see the available pages

<img src="https://user-images.githubusercontent.com/42455466/214470073-6bc71e47-d543-4168-bdcf-93393d945333.jpg" width=30% height=30%>

then

<img src="https://user-images.githubusercontent.com/42455466/214469827-8f26f204-35ea-4833-ad21-0c40da8cfcef.jpg" width=30% height=30%>

**Comment by aidanheerdegen** [comment]
You're not going mad, that is the behaviour I see. You're navigating back to what is the tab level on desktop.

If the behaviour was changeable I would think it would be in one of these options, but I can't see anything appropriate

https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/

**Comment by dougiesquire** [comment]
Annoying. It feels like it would be very easy for a new user to go to check out the website on their phone and come away thinking the website is much smaller than it really is (only the "About" stuff)...

**Comment by aidanheerdegen** [comment]
Yeah, weird. Maybe @rbeucher or @ccarouge have some ideas?

**Comment by rbeucher** [comment]
That's on mobile? Yeah I noticed that too. Will have to correct that.

**Comment by ccarouge** [comment]
There must be a way because [the main site of mkdocs-material](https://squidfunk.github.io/mkdocs-material/) works fine on mobile

**Comment by ccarouge** [comment]
I wonder if the problem is we have subpages under the landing page section. If the landing page was in a section by itself, would we directly get the "tab" navigation from the menu instead of the other pages in the section?
