### ISSUE TITLE
Update "Working Group" tab on Hive to link to more information on the Forum and ACCESS-NRI site

### ISSUE THREAD

**Issue by heidinett** [ACCESS-Hive/access-hive.github.io#274]
Need to update the "Working Groups" page on the Hive (https://access-hive.org.au/working_groups/) so that it points to more information about the Working Groups in the Forum and also on the ACCESS-NRI website (https://www.access-nri.org.au/working-groups/).

**Comment by aidanheerdegen** [comment]
There are some outstanding issues with the fix made in #275 :

- Working groups didn't render as a list
- Links are to the categories not the working group sub-categories
- Some slight rewording would be good

Will put in a PR to fix.
