### ISSUE TITLE
Structure the `getting started` sections in the Hive

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#289]
## Description
Decide upon the content to include in the general `Getting Started` section, and better linking this section to the individual model running requirements. As suggested by Kelsey, having requirements checkboxes in running these models could be one option. 

## Why 
To provide an intuitive user interface for the hive website.

## Close criteria

- [ ] Decide upon location to include models guides and general `getting started` section.
- [ ] Decide upon how to link these section to individual model running sections. Perhaps, using checkboxes as mentioned above...

**Comment by KAUR1984** [comment]
## Description
Decide upon the content to include in the general `Getting Started` section, and better linking this section to the individual model running requirements. As suggested by Kelsey, having requirements checkboxes in running these models could be one option. 

## Why 
To provide an intuitive user interface for the hive website.

## Close criteria

- [ ] Decide upon location to include models guides and general `getting started` section.
- [ ] Decide upon how to link these section to individual model running sections. Perhaps, using checkboxes as mentioned above...

**Comment by KAUR1984** [comment]
Feel free to add any suggestions in this thread regarding the getting started page.

**Comment by atteggiani** [comment]
@svenbuder I assigned myself to this issue, but since you already worked on it a bit, you might want to check it as well.

**Comment by atteggiani** [comment]
@svenbuder I assigned you to this issue after what we discussed today.

**Comment by KAUR1984** [comment]
- [ ] Write the getting started for MED - @svenbuder . 
- [ ] Write the getting started for running a model - @atteggiani .
- [ ] Any common content between the two will be moved to general `getting started`, possibly.

**Comment by svenbuder** [comment]
A solution to this problem will be done as part of #422, where we will introduce "New to modelling? Get Started Here" and "Want to evaluate your model? Get Started Here" button
