### ISSUE TITLE
Glossary of Variables for CMIP, ERA5, UM etc.

### ISSUE THREAD

**Issue by svenbuder** [ACCESS-Hive/access-hive.github.io#292]
**Resources:**
CMIP6: https://clipc-services.ceda.ac.uk/dreq/mipVars.html
ERA5: https://confluence.ecmwf.int/display/CKB/ERA5 and https://sonra.io/data-marketplace/era5-variables/
UM: ? https://ukscience.org/_Media/UM_User_Guide.pdf or https://artefacts.ceda.ac.uk/badc_datadocs/um/umdp_F3-UMDPF3.pdf

**Comment by KAUR1984** [comment]
In order to correctly estimate the effort required to complete this issue, feel free to select the effort estimate taking into account each of the related team members perspective  (with **1** - least effort required, and **40** - highest level of effort required).

**Comment by KAUR1984** [comment]
Since @svenbuder is most familiar with this issue, feel free to add your estimation for level of effort required to complete this issue. As per my perspective, since this issue relates to documentation additions, I have assigned it a level of effort - 1.

**Comment by KAUR1984** [comment]
In case you are not familiar with planning poker, this wiki article gives an intro of what it is used for: https://en.wikipedia.org/wiki/Planning_poker

**Comment by KAUR1984** [comment]
**_Effort_** definition in agile - https://www.parabol.co/templates/agile-estimation/estimated-effort/#:~:text=What%20is%20Agile%20Effort%20Estimation,and%20among%20software%20engineering%20teams.

**Comment by svenbuder** [comment]
Rearranged navigation:
Glossary of Variables shifted under "Community Glossaries" on ACCESS-HIVE:
~/community_resources/glossaries/

Content to be populated

**Comment by rbeucher** [comment]
ERA5-Land variables:

https://collections.eurodatacube.com/reanalysis-era5-land-monthly-means/readme.html

**Comment by rbeucher** [comment]
ERA5 documentation:

https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation#ERA5:datadocumentation-Parameterlistings

**Comment by KAUR1984** [comment]
**_Sprint meeting suggestions [2023.06.26]:_** 

- [ ] Decide upon how to link the ACCESS-NRI glossary and ACCESS-Hive glossaries.
- [ ] Asking @rbeucher suggestions further on this issue.

**Comment by svenbuder** [comment]
Decided with @rbeucher to push this issue back into backlog.
Fix for Legacy Release: Link to the correct CMIP6 and ERA5 Variable portals.
Moved the first version of the searchable html tables with jquery to
https://github.com/svenbuder/access_model_variables

**Comment by svenbuder** [comment]
Closing. Addressed through merging of issue #479.
