### ISSUE TITLE
Brainstorm ways for demonstrating the level of support expected from Hive

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#294]
## Description
Experiment different ways of setting the end-user expectations from the Hive page, i.e., what level of support ACCESS-NRI provide. Currently, the three icons are used to separate the expectations: 

![Screenshot 2023-06-08 at 3.50.19 pm.png](https://images.zenhubusercontent.com/64405d57ad1a46ca689c443b/dcfd338a-01de-4ac8-a404-f1e36dcf23f8)

## Why
For setting clear expectations of what configurations are supported by ACCESS-NRI, recommended by ACCESS-NRI or else, if they are community contributed... 

## Close Criteria
- [ ] Discuss potential ways of highlighting this in the hive page.
- [ ] Subtask - write documentation in an easy-to-follow format, ideally with hands-on examples for users.

**Comment by atteggiani** [comment]
Not relevant anymore
