### ISSUE TITLE
Discussing `Tutorials` sections on the Hive page

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#296]
## Description
Discussing if we need a `tutorials` section for demonstrating examples of running and evaluating models, as suggested by @atteggiani . What content could possibly be included in this `tutorials` section...

## Why
For adding comprehensive model guides on the Hive page for users to dive deeper if they want.

## Close Criteria
- [ ] Discuss the content to include in the tutorials section.
- [ ] Might include some material for the September workshop. 
- [ ] Decide upon whether there should be a separate `tutorials` section or individuals sections. 
- [ ] Implement this on the hive page.

**Comment by KAUR1984** [comment]
In order to correctly estimate the effort required to complete this issue, feel free to select the effort estimate taking into account each of the related team members perspective  (with **1** - least effort required, and **40** - highest level of effort required).

**Comment by KAUR1984** [comment]
As per my perspective, this issue's level of effort is 5. We might clarify the definitions again in the future.

**Comment by KAUR1984** [comment]
Just a friendly reference I found - **_Effort_** definition in agile - https://www.parabol.co/templates/agile-estimation/estimated-effort/#:~:text=What%20is%20Agile%20Effort%20Estimation,and%20among%20software%20engineering%20teams.

**Comment by svenbuder** [comment]
Get back to this later: 
Do we want to put tutorials (e.g. for adjusting specific parts of ESM) as subsections of "Run ESM" and change the current "Run ESM" to a subsection "Run default Setup"

**Comment by svenbuder** [comment]
Get back to this later: 
Do we want to put tutorials (e.g. for adjusting specific parts of ESM) as subsections of "Run ESM" and change the current "Run ESM" to a subsection "Run default Setup"

**Comment by atteggiani** [comment]
Fixed with tutorials page introduction
