### ISSUE TITLE
Add copernicus catalog

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-Hive/access-hive.github.io#298]
https://cds.climate.copernicus.eu/

**Comment by svenbuder** [comment]
On it. Do you envision it to be a link on our community resources, or rather that we ingest the datasets (https://cds.climate.copernicus.eu/cdsapp#!/search?type=dataset) on kj13?

**Comment by rbeucher** [comment]
Oh no just a link. No way we can ingest that.

**Comment by svenbuder** [comment]
Added to access-HIVE:
~/community_resources/community_observational_catalogs.md
