### ISSUE TITLE
Decide upon final structure of the support icons  

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#305]
## Description
Decide upon the final icons to use in the hive page, or whether the new icons should be continued to the legacy release. 

## Why
For the overall UI consistency of the Hive app. 

## Close Criteria
- [ ] Decide and brainstorm ways of the hive icons.

**Comment by KAUR1984** [comment]
As per the docs meeting [2023.06.29],

@NBateman-bit  would possibly be contacting with the UI designer for redesigning the support icons, or possibly icons for tabs on the home page.

**Comment by atteggiani** [comment]
Closing because we decided not to deploy support icons on the website for now.
