### ISSUE TITLE
Check the responsiveness of the HIVE website 

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#307]
## Description
Check the responsiveness of the HIVE website to see how it renders on mobile, iPads and bigger screens.

## Why
For an overall enhanced user experience of the hive website. 

## Close Criteria
- [ ] Check the responsiveness of the website on ipad. 
- [ ] Check the responsiveness of the website on desktops .

**Comment by atteggiani** [comment]
Already dealing with it in #510
