### ISSUE TITLE
Change sizes and order of model configurations

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-Hive/access-hive.github.io#309]
## Description
Making ACCESS Model Configurations in the Model tab (https://access-hive.org.au/development_site/models/) all the same sizes and swap order (1. ACCESS-CM2, 2.ACCESS-ESM1.5, 3.ACCESS-OM2)

## Why
It is visually more appealing

## Close Criteria
- [x] All configuration are same size
- [x] Order is (1. ACCESS-CM2, 2.ACCESS-ESM1.5, 3.ACCESS-OM2)

**Comment by KAUR1984** [comment]
First task completed in issue - #304

**Comment by KAUR1984** [comment]
Fixed in PR - https://github.com/ACCESS-Hive/access-hive.github.io/pull/325

**Comment by KAUR1984** [comment]
Merged in `development` branch.
