### ISSUE TITLE
Make better termynal animations

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-Hive/access-hive.github.io#315]
## Description
Create component to substitute the current termynal.js file for the animations of the terminal

## Why
To make it easier for the developers to put code as a terminal and to allow a better user-experience.

## Close Criteria
- [ ] Create new terminal component and deploy the new component on the website
- [ ] Make sure the component works as expected and includes different options to properly simulate a terminal

**Comment by KAUR1984** [comment]
Try to differentiate background colors from the code blocks @atteggiani .

**Comment by KAUR1984** [comment]
Add a button for turning off the terminal animations. @atteggiani

**Comment by svenbuder** [comment]
PR #498

**Comment by atteggiani** [comment]
Done!
