### ISSUE TITLE
[New Resource]

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-Hive/access-hive.github.io#321]
Hi @svenbuder,

When you have a chance.
It will be great to add 

[cds-api](https://cds.climate.copernicus.eu/api-how-to)

and

[era5cli](https://era5cli.readthedocs.io/en/stable)

These are utilities to download ERA5 data. 

Romain

**Comment by svenbuder** [comment]
Done. Added links to both in the description of the Copernicus Climate Change Service (C3S) data under
~/community_resources/community_observational_catalogs.md

**Comment by svenbuder** [comment]
Trying to close this via PR

**Comment by svenbuder** [comment]
Reopened (sorry Romain)
Auto-closing did not work when linked to branch & pull request, after merging pull request.

**Comment by svenbuder** [comment]
Jasmeen has prepared a great "how to" guide to go into the access-hive/development/README.md. To be discussed next week
