### ISSUE TITLE
Check: old hive content is mapped over

### ISSUE THREAD

**Issue by heidinett** [ACCESS-Hive/access-hive.github.io#338]
Need to check that old Hive content gets mapped over, i.e. finds a home somewhere on the new Hive site.

**Comment by KAUR1984** [comment]
Thanks so much @heidinett ! Also, found this issue in backlog - https://github.com/ACCESS-Hive/access-hive.github.io/issues/291. Were you intending to capture this one or this issue refers to something else sorry?

**Comment by heidinett** [comment]
I think #291 was referring to the ACCESS-NRI homepage<https://www.access-nri.org.au/> --> new Hive, not the old Hive --> new Hive content.




Heidi Nettelbeck                                         [cid:c72bac5e-1fb7-406b-aef9-37de80454fe9]

Team Leader, Atmospheric Modelling Infrastructure

Australian Earth System Simulator (ACCESS-NRI)

T: +61 02 6125 4959 | E: ***@***.******@***.***> | W: access-nri.org.au<https://www.access-nri.org.au/> |

We at ACCESS-NRI acknowledge the Traditional Owners of the land on which our research infrastructure and community operate across Australia and pay our respects

to Elders past and present. We recognise the thousands of years of accumulated knowledge and deep connection they have with all the Earth systems we simulate.


________________________________

**Comment by KAUR1984** [comment]
Edited the title of issue #291 and captured this issue to avoid duplicates -- sprint meeting.
