### ISSUE TITLE
Decision to be made on the choice and placement of Support Icons

### ISSUE THREAD

**Issue by heidinett** [ACCESS-Hive/access-hive.github.io#339]
Final decision needed (at 28.06 meeting): on the choice of Support Icons (Supported, Recommended, Community) and where they are placed so they are easily seen.

**Comment by KAUR1984** [comment]
Thanks so much @heidinett ! Also, found a similar issue in backlog - https://github.com/ACCESS-Hive/access-hive.github.io/issues/305. Very happy to keep either of these issues :)

**Comment by heidinett** [comment]
Agreed. This is addressing the same issue!


Heidi Nettelbeck                                         [cid:02ba43a9-ca15-46ee-9b7e-9dfb43e945ac]

Team Leader, Atmospheric Modelling Infrastructure

Australian Earth System Simulator (ACCESS-NRI)

T: +61 02 6125 4959 | E: ***@***.******@***.***> | W: access-nri.org.au<https://www.access-nri.org.au/> |

We at ACCESS-NRI acknowledge the Traditional Owners of the land on which our research infrastructure and community operate across Australia and pay our respects

to Elders past and present. We recognise the thousands of years of accumulated knowledge and deep connection they have with all the Earth systems we simulate.


________________________________

**Comment by KAUR1984** [comment]
Closing this issue to avoid duplicates. -- sprint meeting.
