### ISSUE TITLE
Possible redesign of "Home" tab contents and structure

### ISSUE THREAD

**Issue by heidinett** [ACCESS-Hive/access-hive.github.io#340]
Need consensus if we should condense the content of landing page of Hive "Home" so that the information is presented in tiles that can be expanded when you click on them (like that in the model components to avoid using too much text and having to scroll). At present, you have to scroll down to find more information such as the Support Icons, etc.

**Comment by KAUR1984** [comment]
New implementation merged in `development` branch. 

![Screenshot 2023-07-13 at 12 49 40 pm](https://github.com/ACCESS-Hive/access-hive.github.io/assets/42607679/461de34c-9438-4441-bb72-6a507c871ab9)

**Comment by KAUR1984** [comment]
Might need to redesign the home page entirely, so keeping this issue open for the future. Moving to parked.

**Comment by KAUR1984** [comment]
Since, redesigning of the home page is in progress. Hence moving this issue to in-progress :)

**Comment by KAUR1984** [comment]
Related issue - #457

**Comment by KAUR1984** [comment]
Closing as duplicate
