### ISSUE TITLE
Final decision: Need to lock in high-level navigation of Hive tabs 

### ISSUE THREAD

**Issue by heidinett** [ACCESS-Hive/access-hive.github.io#342]
Decision needed (in meeting 28.06): lock in high-level navigation of Hive tabs and their contents to complete skeleton of new Hive layout.

**Comment by svenbuder** [comment]
Suggestions for restructured MED and Community high-level Navigation below.


![med_navi.png](https://images.zenhubusercontent.com/6466c5964c9274b41b4b424e/f83750cc-570a-4f87-8102-9acd8be876be) ![community_navi.png](https://images.zenhubusercontent.com/6466c5964c9274b41b4b424e/4db38e44-9933-4959-ba4c-7a501aebe8af)

**Comment by KAUR1984** [comment]
_Suggestions from sprint meeting:_ 
High-level navigation decided in the bigger team meeting on wednesdays.

**Comment by KAUR1984** [comment]
Closing this issue
