### ISSUE TITLE
Update example in Atmosphere component: How UM is used?

### ISSUE THREAD

**Issue by heidinett** [ACCESS-Hive/access-hive.github.io#344]
Old Hive content and ACCESS-NRI website mentions BOM use of UM in ACCESS model for weather forecasting. (This has been commented out in recent PU that edits the Atmosphere component text).
Might be more applicable to include an example in Atmosphere component (How UM is used?) that refers to ACCESS-CM or ESM?

**Comment by KAUR1984** [comment]
_Suggestions from Sprint meeting:_

- Moving this issue to backlog for discussion, possibly. 
- @heidinett would be awesome if you could add the rough effort required for this issue. 
- And also selecting which release this issue belongs to (in the right side bar).
