### ISSUE TITLE
Where should additional info on "Gadi Resources" live?

### ISSUE THREAD

**Issue by heidinett** [ACCESS-Hive/access-hive.github.io#346]
Where should additional info on "Gadi Resources" live? (e.g. more general info on PBS jobs, storage and compute). This used to reside in the old access-docs "Getting started" info. Is it still needed or should we omit it from new Hive content?

**Comment by svenbuder** [comment]
I have added it as a 4th Section in the **Computing Access (Gadi@NCI)** file.
See pull request #354

**Comment by KAUR1984** [comment]
PR merged.
