### ISSUE TITLE
Review choice of image and text for "Acknowledgement of Country" and "Contribute to ACCESS-Hive"

### ISSUE THREAD

**Issue by heidinett** [ACCESS-Hive/access-hive.github.io#347]
Review needed on the choice of image and text for "Acknowledgement of Country" and "Contribute to ACCESS-Hive" on "Home" tab (landing page).

**Comment by NBateman-bit** [comment]
I have several suggestions for this area. Should I upload the images here or in Sharepoint?

**Comment by svenbuder** [comment]
From @NBateman-bit : Hi all, I have created a folder with all the suggested images for each of the sessions here: https://anu365.sharepoint.com/:f:/r/sites/ACCESS-NRI/Shared%20Documents/ACCESS-Hive?csf=1&web=1&e=KKG9UK

**Comment by KAUR1984** [comment]
Closing as happy with the current implementation -- team sprint meeting. Thanks @NBateman-bit
