### ISSUE TITLE
Fix coloscheme of whole website using ACCESS-NRI colors + light mode

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-Hive/access-hive.github.io#352]
## Description
1. Fix the color scheme of the whole website by creating appropriate CSS variables (overwriting the markdown ones if necessary) to define custom colors for different elements (e.g. links, link hover, tabs, foreground, background..) and link **ALL** colors used on the website to those variables.
Use access NRI main 5 colors (from ACCESS-NRI main logo) when possible.
These colors are:
- green: #A6CE39;
- orange: #FAA619;
- dark-blue: #115D97;
- blue: #06AEEF;
- light-blue: #8ED7F8;

2. Set up light mode with appropriate color scheme, adding the switcher at the top of the page.

## Why
1. To have a better consistency with ACCESS-NRI main website and have a better 'branding'.
2. To improve the user experience by having both dark and light modes.

## Close Criteria
- [x] Create custom variables for colors, including the 5 main ACCESS-NRI colors.
- [x] Link ALL colors used in the website to the custom variables, using one of the main 5 NRI colors when possible.
- [x] Set light mode with appropriate color scheme and switcher at the top of the page.

**Comment by KAUR1984** [comment]
Merged in `development` branch.
