### ISSUE TITLE
Link Live-Diagnostics in "How to Run a Model"

### ISSUE THREAD

**Issue by svenbuder** [ACCESS-Hive/access-hive.github.io#353]
Mike Tetley is writing "live-diagnostics" tools for all ACCESS configurations.
They will allow people to check output etc. at specified time steps while a Model is running.

@atteggiani and @KAUR1984: We should chat with Mike how the inclusion of Mike's code in the "Run a Model" sections could look like.

The description of the "live-diagnostics" tool on ACCESS-HIVE will be at:
`docs/model_evaluation/model_evaluation_live_diagnostics.md`

**Comment by atteggiani** [comment]
That sounds pretty good! 
In the meeting we can talk more about it and decide how to address that.

**Comment by KAUR1984** [comment]
Awesome! I agree.

**Comment by KAUR1984** [comment]
_-- Sprint meeting suggestions:_ 

Might take some time to integrate with Hive, hence moving to backlog.
