### ISSUE TITLE
Should the HIVE-Navigation left be expanded or expandable?

### ISSUE THREAD

**Issue by svenbuder** [ACCESS-Hive/access-hive.github.io#355]
Options:

Expanded: users see all subsections etc. and can directly go to more detailed content (useful for experienced users). Might be bad/too crowded, if we have too many sections/subsections/subsubsections

Expandable: clearer overview, but we would need really good and descriptive section titles (otherwise users may not be able to find more detailed content).

Switching on/off is adjusted in mkdocs.yml:
```
features:
  - navigation.expand
```

Examples of the opens attached.

![expandable.png](https://images.zenhubusercontent.com/6466c5964c9274b41b4b424e/5e7dd807-2fdf-4f0a-8e4f-28a1b6dd5f70)

![expanded.png](https://images.zenhubusercontent.com/6466c5964c9274b41b4b424e/6989d0b0-18bb-438b-b8e4-d7f382eeb8c2)

**Comment by KAUR1984** [comment]
My personal preference would be to have it as `expandable`, so as to get a high level picture first and then go to the relevant topics inside. We could aim for only two nesting levels in the navigation, they can quickly navigate to the topics, but very much down to suggestions from the team :) .

**_Examples of closed navigation_**:

1. https://fastapi.tiangolo.com
2. https://docs.github.com/en/get-started

**Comment by KAUR1984** [comment]
Closing as decided for the legacy release :) Might just create another issue for tweaks in the future.
