### ISSUE TITLE
Change the name of `Table of contents` to `In this article` on Hive

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#370]
## Description
As per the suggestions in the sprint meeting, currently, `table of contents` heading is a bit confusing and is somewhat conflicting with the main navigation on the left. Hence, need to change the name of `table of contents` on the right (offered by MkDocs) to `in this article` heading or perhaps, something similar. 

## Why
To avoid confusion between the two navigations on Hive, and proper utilisation of the benefits of two navigations.

## Close Criteria
- [x] Change the name of `table of contents` to `in this article` or other on hive.
- [x] Adjust the color of `table of contents` to be of lighter color than the main navigation.
- [x] Increase the margin below the headings of the sidebars. 
- [x] Increased the font-size of the left sidebar (main sidebar) slightly.
- [x] Added `right-margin` to the support icons (for having equal left and right margins).

**Comment by KAUR1984** [comment]
Suggestions from the team needed: 

> First Implementation ("On this page")

<img width="1512" alt="Screenshot 2023-07-04 at 2 37 54 pm" src="https://github.com/ACCESS-Hive/access-hive.github.io/assets/42607679/bdd2c138-1111-490c-971d-21a5b37553ad">

> Second implementation ("In this article")

<img width="1512" alt="Screenshot 2023-07-04 at 2 36 38 pm" src="https://github.com/ACCESS-Hive/access-hive.github.io/assets/42607679/749e6eb4-7b63-4563-b0ed-a3c25688faa7">

**Comment by KAUR1984** [comment]
Feel free to add your preference in this issue thread: 

- Happy with either headings, slightly more preference for the `On this page` heading.

**Comment by KAUR1984** [comment]
I am happy with either headings, slightly more preference for the `On this page` heading.

**Comment by atteggiani** [comment]
I prefer `On this page` too :)

**Comment by KAUR1984** [comment]
Created PR - https://github.com/ACCESS-Hive/access-hive.github.io/pull/387

On branch - https://github.com/ACCESS-Hive/access-hive.github.io/tree/jasmeen/change-toc-heading-370

**Comment by NBateman-bit** [comment]
I think "On this page" is better

**Comment by KAUR1984** [comment]
Thanks @NBateman-bit and @atteggiani !
