### ISSUE TITLE
Decide id support icons go before or after the element

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-Hive/access-hive.github.io#390]
## Description
Support icons sometimes are placed before the element (), sometimes after (https://access-hive.org.au/development_site/models/model_components/atmosphere/). 

## Why
UI Improvements

## Close Criteria
- [ ] Set support icons before or after.

Notes:
A smart way to implement the icons might be to add ::after or ::before pseudo-selectors to the icons' classes.

**Comment by KAUR1984** [comment]
At some places, we are using icons somewhere before and after the text, might need to be consistent with the placement of the icons. Closing this issue now as we decided to not to use icons in the near future.
