### ISSUE TITLE
Too many contact options

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-Hive/access-hive.github.io#393]
## Description
https://access-hive.org.au/development_site/about/contact/#other-places-where-you-can-find-the-access-nri-team includes LinkedIn, twitter and slack

Do we really want users contacting us via any of these?, E.g. we've discussed going to paid team only slack and even if anyone is looking at twitter or LinkedIn it would have to be redirected to the forum to get a response. Even github isn't ideal.

## Why

Simplify communications

## Close Criteria
Decision on whether these are actively supported or delete the whole subsection.

**Comment by KAUR1984** [comment]
I agree. Thanks for flagging this @MartinDix !

**Comment by atteggiani** [comment]
New issue on this #491
