### ISSUE TITLE
ICONS: Remove `support` icons from the Hive page

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#406]
## Description
As per the meeting discussions, we should possibly remove all the _support_ icons from the Hive page. 

## Why
Not needed currently.

## Close Criteria 

- [x] Remove all the support icons from the Hive for the legacy release (by commenting out in the code, perhaps not removing them entirely).

**Comment by atteggiani** [comment]
Merged. Closing
