### ISSUE TITLE
UI: Proper styling of the contact icons/links on the `Contact` page

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#407]
## Description
Proper styling needs to be of the contact icons/links on the `Contact` page. Currently, the linking is seeming opposite as the ACCESS-NRI keyword is linked and not the actual platforms. 

 ![Screenshot 2023-07-06 at 4.27.07 pm.png](https://images.zenhubusercontent.com/64405d57ad1a46ca689c443b/a9232aec-6f22-4bba-8aa6-932b17a2eb17)

## Why
For enhanced user experience of the hive website. 

## Close Criteria

- [ ] Brainstorm ways of improving the contact icons UI.
- [ ] Change the icons of ACCESS-Hive forum.
- [ ] Implement the changes.

**Comment by atteggiani** [comment]
New issue on this #491
