### ISSUE TITLE
Warning/Information sign or badge "What's to come"

### ISSUE THREAD

**Issue by svenbuder** [ACCESS-Hive/access-hive.github.io#420]
Similar to the "Call for contribution" warning:

Green "What's to come" sign with what we are working on below.

Or do we want a "badge" for the "state of release": planned / in-progress / released?

![Screen Shot 2023-07-12 at 12.23.42 pm.png](https://images.zenhubusercontent.com/6466c5964c9274b41b4b424e/cb7622c6-558a-47cf-9fce-591449871e9d)

**Comment by KAUR1984** [comment]
Sven suggested that - may be for the MED content, could have a message at the end of what is currently in development.

**Comment by svenbuder** [comment]
There are many default options available for MKDOCS. see here: https://squidfunk.github.io/mkdocs-material/reference/admonitions/
I attach a screenshot of the ones I would see as most fitting (if we want to use such fields)

![mkdocs_fields.png](https://images.zenhubusercontent.com/6466c5964c9274b41b4b424e/be031c14-982f-4bfd-ab3a-30e18f862cb0)

**Comment by KAUR1984** [comment]
**_Terms clarification (discuss how to clarify the warnings):_** 

**Ownership** 
Written and supported by ACCESS-NRI. Ex. Intake Catalog

**Support**
ESMVal tool (can help to keep it running on gadi)

**Comment by svenbuder** [comment]
To discuss at Meeting on 2nd August:

"We own and support the code" vs. 
"We do not own the code but support it" vs.
"We neither own it nor support it"

**Comment by svenbuder** [comment]
Addressed with #499
