### ISSUE TITLE
HOME PAGE: Finalise the subsections to include on the home page. 

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#422]
## Description

Decide upon the final home page content and what sub-sections should be included (for ex. policies, license etc.), or find any additional placeholders where these sections could be included. 

## Why

For enhancing the clarity of sections across the hive page. 

## Close Criteria

- [ ] Brainstorm ways of improving the home page categories. 
- [ ] Implement the final UI on the hive page.

**Comment by svenbuder** [comment]
![Screen Shot 2023-07-14 at 3.24.55 pm.png](https://images.zenhubusercontent.com/6466c5964c9274b41b4b424e/13cf9e83-c0e8-4e46-b3eb-338b72675c06)

**Comment by svenbuder** [comment]
Center "Navigation ACCESS-HIVE"
Add  box around?

**Comment by svenbuder** [comment]
@NBateman-bit : exchange acknowledgement of country picture with splash landscape pictures

**Comment by svenbuder** [comment]
Ideas for buttons at top of homepage
"Coding Errors? How to Get Help"
"Lost with an acronym? To our Glossary"
"You wrote a useful tool? How to contribute"
"New to ACCESS Models? Get started here"
"Want to evaluate your model? Get started here"

**Comment by svenbuder** [comment]
Linked this issue with branch "dev/homepage".
https://github.com/ACCESS-Hive/access-hive.github.io/tree/dev/homepage

**Comment by MartinDix** [comment]
I like the idea of the buttons, but the "How to get support" button text is invisible in firefox light mode (until mouse over).

Change HIVE to Hive to be consistent.

Image under Acknowledgement of Country doesn't match the unsplash link. In any case, I wouldn't have images of rock art whose potential significance we don't understand.

**Comment by svenbuder** [comment]
Great points, @MartinDix. We will hopefully manage to fix those tomorrow morning.

**Comment by atteggiani** [comment]
Closing as new relateed issue (#457) created.
