### ISSUE TITLE
COMM. RESOURCES: Restructure the community resources tab on hive

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#425]
## Description

The community resources tab could possibly be renamed to the `resources` tab, which could have a subsection `community` inside. Need discussion with the team. 

## Why

For avoiding any ambiguities and being too specific or too loose in the naming of the tabs.

## Close Criteria

- [ ] Discuss with the team for the final structure of the comm. resources tab.

**Comment by svenbuder** [comment]
@NBateman-bit 

We will restructure the Community Resource / EVENTS page to link to the currated "Events"
+ Add information on this event page on "How to Contact us to add your event to the List"

**Comment by svenbuder** [comment]
First adjustments introduced with PR "Cleaned up Community Resources Tab" #444:

- adjusted Events section to link to ACCESS-NRI website
- Model Evaluation Links now has an overview page.

**Comment by svenbuder** [comment]
Make sure the FOOTER is working at the end of .md files with tables.

![Screen Shot 2023-08-02 at 12.40.57 pm.png](https://images.zenhubusercontent.com/6466c5964c9274b41b4b424e/00d14111-9462-4f41-a453-bc60863bcef3)
