### ISSUE TITLE
MODELS: Rename the `ACCESS models` heading to `Supported ACCESS Models` 

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#426]
## Description

Possibly change the ACCESS models heading to just supported models [subject to discussion from the team].

## Why

For avoiding any ambiguities in naming the tabs in the navigation bar. 

## Close Criteria

- Discuss with the team for the proper naming of the Models tab.

**Comment by atteggiani** [comment]
- [x] renamed title "ACCESS Models" to "Supported ACCESS Models"
- [x] renamed title "Model Configurations" to "Supported Model Configurations"
- [x] Switched position of access components and access configurations
- [x] Other minor adjustments to some titles (highlighted background)
