### ISSUE TITLE
Rationalise navigation structure for launch

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#43]
Based on feedback from soft launch, reduce/review navigation structure to remove empty sections.

**Comment by ccarouge** [comment]
@aidanheerdegen I think we're done here? We might need a new section or tab somewhere for #207 or #182 but that's normal evolution of the site.

**Comment by rbeucher** [comment]
Yes I agree. Closing this one.
