### ISSUE TITLE
UI: Make all the image fonts and positioning consistent across Hive

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#435]
## Description
Currently, the images used have some inconsistencies in terms of sizes, colors, labels positioning and font size and style.

![Screenshot 2023-07-14 at 1.23.52 pm.png](https://images.zenhubusercontent.com/64405d57ad1a46ca689c443b/8ac7f714-5263-4f41-932b-f9ad8a6fc8f2)

![Screenshot 2023-07-14 at 1.24.21 pm.png](https://images.zenhubusercontent.com/64405d57ad1a46ca689c443b/22e06526-7f5e-4aff-a139-2976f1e3d4b5)

## Why
For ensuring consistency across the hive page.

## Close Criteria
- [ ] Fix the consistency issues between the images used on the hive.

**Comment by KAUR1984** [comment]
**_Suggestions from the team:_** 

-- @heidinett 
> For the image in ACCESS-AM, is it possible to reduced the font size of "ACCESS-AM" heading to match the same size of the other configuration headings? 

 -- @atteggiani 
> To also make ACCESS-OM2 the same fontsize as the other ones. (Basically use the same fontsize for all the configurations);
To change the ACCESS-CM2 component name from "land surface" to "land", as in the other configurations that use it (ESM and AM)

**Comment by heidinett** [comment]
Images look good and seem to fit well within rectangular card margins for the 4 different model configurations. 
Thanks Jasmeen!

**Comment by KAUR1984** [comment]
Completed with basic images on the hive.
