### ISSUE TITLE
HOME PAGE development

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-Hive/access-hive.github.io#457]
## Description
Restructure Homepage

Ideas for buttons at top of homepage
"Coding Errors? How to Get Help"
"Lost with an acronym? To our Glossary"
"You wrote a useful tool? How to contribute"
"New to ACCESS Models? Get started here"
"Want to evaluate your model? Get started here"

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3634363663353936346339323734623431623462343234652f31336366396538332d633065382d346534362d623365622d333338623732363735633036.png](https://images.zenhubusercontent.com/637da12d354b8191c47b9885/7dc06c4c-7c1e-43ca-80e4-70298fa26829)

## Why
Improve UI

## Close Criteria
- [ ] Structure new HOMEPAGE

**Comment by KAUR1984** [comment]
Related issue - #340

**Comment by atteggiani** [comment]
Glossary and FAQ --> Small ones after the cards

**Comment by atteggiani** [comment]
Written homepage for External review
