### ISSUE TITLE
Edit "How To Get Support" Content

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#460]
## Description
We have a "How To Get Support" button on the Homepage.
It should guide the users to a page describing the different types of support (coding support, support for Hive etc.) and how to get this support.

## Close Criteria
- [ ] Create it as an index.md page anywhere in docs.
- [ ] Describe the different types of user support we provide
- [ ] Add Buttons with links to the correct pages where people can get support (Hive Forum #help etc.).
- [ ] We will link the page on the homepage once this issue is closed.

**Comment by ccarouge** [comment]
@aidanheerdegen before starting on a draft, would it help to clarify what "different types of support" means? It isn't clear to me.

**Comment by aidanheerdegen** [comment]
> @aidanheerdegen before starting on a draft, would it help to clarify what "different types of support" means? It isn't clear to me.

That wasn't written by me, so I suppose this is a description of the "in-scope" support of releases vs the general help/assistance for other queries (including help from the community).

We should point directly to forum topics for some of this stuff. Linking to topics that are currently in a closed category is fine, we can move them when we officially launch and the link will be unchanged.

**Comment by atteggiani** [comment]
Integrate FAQ button in the "Get Support" button on the Homepage --> "FAQs / Get Support"

Integrate FAQ page in the About > User Support page, showing FAQs first, and then the User Support (Forum) in case people still need help.
Connected to #493
