### ISSUE TITLE
CONTRIBUTE TAB: Restructure the contribute page to have clear instructions

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#462]
## Description

Restructure the `contribute` page to have clear instructions of how end-user could contribute to the development of the hive page.

## Why

To provide clear contribution instructions for the end-users to contribute to the hive page.

## Close Criteria

- [x] Restructure and implement the revised `how to contribute` page.

**Comment by KAUR1984** [comment]
Team meeting: Might need to explore options for a full structure of `how to contribute` page.

**Comment by svenbuder** [comment]
2 Categories on how to Contribute:
- raise a Github issue (and create branch+PR for advanced users)
- post your suggestion on the Hive Forum

**Comment by KAUR1984** [comment]
Restructure the `user support` page with the latest FAQ section.

**Comment by KAUR1984** [comment]
Increase the font-size of the faq section
