### ISSUE TITLE
CONFIGURATIONS: Shorten the text in the configuration card to one-two-liners

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#465]
## Description
The text in the rectangular cards is quite long and that could be possibly reduced. 

![Screenshot 2023-07-20 at 1.54.40 pm.png](https://images.zenhubusercontent.com/64405d57ad1a46ca689c443b/3c47437c-794a-4833-a8e2-4729b5c80939)

## Why

For less scrolling on the home page. 

## Close Criteria

- [ ] Shorten the text in the `model configurations` to one-two-liners as per the suggestions from @heidinett

**Comment by heidinett** [comment]
I agree with @KAUR1984. I also think we can remove the headings on the configuration images as they appear in the text.
Are these text snippets better:

ACCESS-CM is a global climate model that includes the atmosphere, land, ocean and sea-ice components, and produces physical climate simulations.

ACCESS-ESM is a global climate model that also includes land and ocean biogeochemical components to simulate both the physical climate and global biogeochemical cycles.

ACCESS-OM is a global coupled ocean and sea ice model used to understand both physical and biogeochemical processes in the ocean.

ACCESS-AM is a global climate model that includes atmosphere and land components, driven by historical sea surface temperature and ice data.
