### ISSUE TITLE
Update Model Data section

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-Hive/access-hive.github.io#466]
The language used to describe the ACCESS-NRI Intake catalog in the Model Evaluation/Model Data section is a little different than that used in the dedicated [ACCESS-NRI Intake catalog documentation](https://access-nri-intake-catalog.readthedocs.io/en/latest/usage/index.html). I think this should be updated to avoid confusion.

Happy to submit a PR.

**Comment by svenbuder** [comment]
Yes, very important point @dougiesquire. The content is currently based on the first content of the intake documentation (including now outdated links to github documentation).

Love the new documentation setup. I was wondering if we maybe should just have a minimum text + overview of the "products" on the Hive and link over to your documentation?

**Comment by atteggiani** [comment]
@svenbuder and @dougiesquire, did you decide how to go with this? 

I think it's important to have consistency between the Hive and other related documentations of the same tools.

**Comment by dougiesquire** [comment]
We merged a PR for this earlier today - see https://github.com/ACCESS-Hive/access-hive.github.io/pull/477
