### ISSUE TITLE
Add METPlus to the MED Section (supported framework)

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-Hive/access-hive.github.io#474]
METPlus
https://dtcenter.org/community-code/metplus

METPlus documentation
https://metplus.readthedocs.io/en/latest/

METPlus on NCI
https://forum.access-hive.org.au/t/metplus-5-0-available-at-nci/810

@svenbuder

**Comment by svenbuder** [comment]
Solved with merging of #478
