### ISSUE TITLE
FROM SLACK: Review `how to run ACCESS-OM` page

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#483]
## Description (from slack)

On run `ACCESS-OM`, and section Get ACCESS-OM configuration , demo code cd ~/access-eom  should be cd ~/access-om
11:25
Another small edit maybe, on Run ACCESS-OM, and section Edit ACCESS-OM configuration , it could be worth being explicit that you need to be in cloned repo cd ~/access-om/1deg_jra55_iaf before  running git checkout -b example_run

## Why

Addressing the slack comments for improving the access-om page. 

## Close Criteria

- [ ] Fix the above mentioned suggestions on the slack channel.

**Comment by KAUR1984** [comment]
**_Reply on slack (Davide):_** 
Yeah I understand that.
I think we might get away with giving detailed information about the important configuration parameters that will (likely) not change, and then maybe give a brief description of the remaining, specifying that since the configurations are in constant evolution there might be minor differences with the documentation on the Hive.
(Of course we will still try to keep everything up to date but I can understand it will be very hard with everything changing) (edited)

**Comment by KAUR1984** [comment]
Reply from @aidanheerdegen  (on slack) : 

For the runlog: true description, I would say this should never be changed to false unless you really know what you’re doing. runlog is crucial for keeping track of the progress of an experiment.
(TBH it is true by default and should be removed from the configurations IMO) (edited)

**Comment by aidanheerdegen** [comment]
> I think we might get away with giving detailed information about the important configuration parameters that will (likely) not change, and then maybe give a brief description of the remaining, specifying that since the configurations are in constant evolution there might be minor differences with the documentation on the Hive.

At this stage I don't think we were planning on versioning these docs. The intention being they were general enough that it didn't matter if some of the minor detail changed as these were quite top-level. Configuration specific detail should go in versioned docs associated with configurations.

**Comment by atteggiani** [comment]
Done
