### ISSUE TITLE
SLACK: General fixes on the hive 

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#485]
## Description

These suggestions are received on slack and are considered as mostly quick fixes on the hive. 

## Why

For fixing any hiccups in the UI experience.

## Close Criteria

- [ ] Fix all the below suggestions for fixing on the hive.

**Comment by atteggiani** [comment]
Sean Bryan
:house_with_garden:  [3:12 PM](https://access-nri.slack.com/archives/C05JD5D1NBA/p1689829955766979)
On [Run a Model](https://access-hive.org.au/development_site/models/run-a-model/) the “how to get started” link on the first line of the page should go to https://access-hive.org.au/development_site/get_started/ instead of https://access-hive.org.au/get_started

**Comment by atteggiani** [comment]
re: https://access-hive.org.au/development_site/community_resources/
Broken image links.

**Comment by KAUR1984** [comment]
Harshula
  [3:37 PM](https://access-nri.slack.com/archives/C05JD5D1NBA/p1689831459038339)
re: https://access-hive.org.au/development_site/model_evaluation/#tools-in-development
Horizontally squashed images

**Comment by KAUR1984** [comment]
re: [https://access-hive.org.au/development_site/model_evaluation/model_evaluation_on_gadi/model_evaluation_on_gadi_esmvaltool/#esmvaltool-[…]es-examples](https://access-hive.org.au/development_site/model_evaluation/model_evaluation_on_gadi/model_evaluation_on_gadi_esmvaltool/#esmvaltool-recipes-examples)
Broken image links?

**Comment by KAUR1984** [comment]
Felicity Chun
  [3:49 PM](https://access-nri.slack.com/archives/C05JD5D1NBA/p1689832192118389)
[Community working groups](https://access-hive.org.au/development_site/community_resources/community_working_groups/) - in dark mode can we crop the icons for COSIMA and Forecasting and prediction to the circles so you don't see the white box around

**Comment by KAUR1984** [comment]
Harshula
  [3:50 PM](https://access-nri.slack.com/archives/C05JD5D1NBA/p1689832234259999)
re: Page Title
Is there another way to emphasise the Page Title without the background colour change? At the moment the colour is out of place, particularly for the light theme. e.g. Font size and/or font decoration?

**Comment by KAUR1984** [comment]
Dale Roberts
  [4:10 PM](https://access-nri.slack.com/archives/C05JD5D1NBA/p1689833417599559)
Pedantic nitpick: On this page https://access-hive.org.au/development_site/get_started/#log-in-to-gadi, please encourage Windows users to use Windows Subsystem for Linux (https://learn.microsoft.com/en-us/windows/wsl/install), terminal emulators have been obsolete on Windows for years!

**Comment by KAUR1984** [comment]
Max Proft
  [8:38 AM](https://access-nri.slack.com/archives/C05JD5D1NBA/p1689892726640619)
https://access-hive.org.au/development_site/models/configurations/access-am/#other-configurations
You have written Citation 1 and link to the paper. At the bottom you have the written citation.
Put the "1" at the end of text, make the full citation at the bottom of the page link to the paper (i.e. do it similar to wikipedia)

**Comment by KAUR1984** [comment]
Australian English: Catalogue, not Catalog
https://access-hive.org.au/pr-preview/pr-458/model_evaluation/model_evaluation_observational_catalogs/

**Comment by atteggiani** [comment]
"How to run" pages.
Remember to fix any "TO DO" left in the text

**Comment by svenbuder** [comment]
Getting Started page, join relevant projects. Missing uppercase to Gadi:
`If you want to change your default project, please check how to change your default project on gadi.`

**Comment by KAUR1984** [comment]
Martin Dix
  [10:42 AM](https://access-nri.slack.com/archives/C05JD5D1NBA/p1690332138390459)
Model images at https://access-hive.org.au/development_site/models/run-a-model/ aren't the same as the updated versions in https://access-hive.org.au/pr-preview/pr-471/models/

**Comment by KAUR1984** [comment]
Davide (He/Him)
  [11:12 AM](https://access-nri.slack.com/archives/C05JD5D1NBA/p1690333970421329)
Restructure the footer (take inspiration from NRI website)

**Comment by atteggiani** [comment]
Getting Started page, [Automate the log in step](https://access-hive.org.au/development_site/get_started/#automate-the-log-in-step):
If you are running a MacOS versions
remove “s” at version.

**Comment by atteggiani** [comment]
Getting Started page, [Automate the log in step](https://access-hive.org.au/development_site/get_started/#automate-the-log-in-step): under Create/Update the SSH config file, replace:
The ~/.ssh/config file is a file where you can store the SSH configurations for different servers, labeled so you don’t have to remember them.
with
The ~/.ssh/config file is a file where you can store labelled SSH configurations for different servers so you don’t have to remember them.

**Comment by atteggiani** [comment]
Getting Started page, [change default project](https://access-hive.org.au/development_site/get_started/#change-default-project-on-gadi):
I don’t understand why it says:
It is recommended that you change your default project on Gadi, as this might be used by tasks such as running a model or model evaluation.
Why would people change it if it is set to their default computational project?
Shouldn’t it rather be:
It is recommended that you check what your default project on Gadi is set to. The default project should be set to the computational project you will most likely use to run simulations/forecasts and store data. (edited)

**Comment by KAUR1984** [comment]
Claire Carouge
:palm_tree:  [4:01 PM](https://access-nri.slack.com/archives/C05JD5D1NBA/p1690351271367929)

[ACCESS-CM page](https://access-hive.org.au/development_site/models/configurations/access-cm/): move the graphic to the top (above the text) to be the same as the other model configuration pages.

**Comment by atteggiani** [comment]
Add steps to copy authorized keys in the Get Started page

**Comment by atteggiani** [comment]
> re: [https://access-hive.org.au/development_site/model_evaluation/model_evaluation_on_gadi/model_evaluation_on_gadi_esmvaltool/#esmvaltool-[…]es-examples](https://access-hive.org.au/development_site/model_evaluation/model_evaluation_on_gadi/model_evaluation_on_gadi_esmvaltool/#esmvaltool-recipes-examples) Broken image links?

@svenbuder can you please do something about this? 
The image you reference in the `.md` file simply don't exist.

**Comment by atteggiani** [comment]
Merged
