### ISSUE TITLE
FROM SLACK: Show next steps or links to follow after components, configurations and running a model

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#487]
## Description
Harshula
  3:41 PM
re: https://access-hive.org.au/development_site/models/configurations/access-om/#access-om2
Would a link at the end to the "Run ACCESS-OM" page be helpful to the reader?

Davide (He/Him)
  7 days ago
Yeah. We still have to add links to the various "How to run" pages, but I think they should definitely go at the end of each Model configuration page and some other pages we think it could be useful!

**Comment by atteggiani** [comment]
Addressed with #532
