### ISSUE TITLE
FROM SLACK: Legacy Release Comments for MED

### ISSUE THREAD

**Issue by svenbuder** [ACCESS-Hive/access-hive.github.io#490]
Includes fixes to:

- [x] Opening line, change to "ACCESS-NRI's Model Evaluation and Diagnostics (MED) ..."
- [x] [here](https://access-hive.org.au/pr-preview/pr-458/model_evaluation/model_evaluation_getting_started/) Side panel calls it "Model evaluation on Gadi". but the image has "MED Conda Environment". Be consistant.
- [x] [here](https://access-hive.org.au/pr-preview/pr-458/model_evaluation/) same
- [x] [MED Observational Data Catalog](https://access-hive.org.au/pr-preview/pr-458/model_evaluation/model_evaluation_observational_catalogs/): Boxes look strange
- [x] [Here](https://access-hive.org.au/pr-preview/pr-458/model_evaluation/model_evaluation_observational_catalogs/) Why is the NCI ESGF Node under Observational Data Catalog? I think all the local data is model data (CMIP, CORDEX...) not observational data. -> Check if already taken out.
- [x] [MED on GADI](https://access-hive.org.au/pr-preview/pr-458/model_evaluation/model_evaluation_on_gadi/) "At the moment, we are actively supporting:" - What parts are we supporting? Explain what support means.
- [x] [here](https://access-hive.org.au/pr-preview/pr-458/model_evaluation/model_evaluation_on_gadi/model_evaluation_on_gadi_esmvaltool/#esmvaltool[…]es-examples) image links broken
- [x] [here](https://access-hive.org.au/pr-preview/pr-458/community_resources/) image links broken...
- [x] [MED Getting Started](https://access-hive.org.au/development_site/model_evaluation/model_evaluation_getting_started/model_evaluation_getting_started/#2-what-is-part-of-the-access-med-enrivonment) Include instructions on how to get juptyer running (to the point where you can import relevant packages).

**Comment by atteggiani** [comment]
Australian English: Catalogue, not Catalog
https://access-hive.org.au/pr-preview/pr-458/model_evaluation/model_evaluation_observational_catalogs/

**Comment by atteggiani** [comment]
https://access-hive.org.au/pr-preview/pr-458/model_evaluation/model_evaluation_observational_catalogs/ MED Observational Data Catelog]: Boxes look strange

**Comment by atteggiani** [comment]
https://access-hive.org.au/pr-preview/pr-458/model_evaluation/model_evaluation_getting_started/
Side panel calls it "Model evaluation on Gadi". but the image has "MED Conda Environment". Be consistant.

Here too https://access-hive.org.au/pr-preview/pr-458/model_evaluation/

**Comment by atteggiani** [comment]
Why is the NCI ESGF Node under Observational Data Catalog? I think all the local data is model data (CMIP, CORDEX...) not observational data.
https://access-hive.org.au/pr-preview/pr-458/model_evaluation/model_evaluation_observational_catalogs/

**Comment by svenbuder** [comment]
All issues addressed. PR standing to ingest last change (language editing of catalog -> catalogue)

**Comment by svenbuder** [comment]
All points addressed.
