### ISSUE TITLE
FROM SLACK: NCI Project List on `Getting Started`

### ISSUE THREAD

**Issue by svenbuder** [ACCESS-Hive/access-hive.github.io#492]
From A:
[On this page](https://access-hive.org.au/development_site/get_started/):
There is a list of projects that people can join. I'm not sure about listing all of these, because not all of them are owned by us, and it's not up to us to say which project people should join. I would instead phrase this to say (1) you have to join a compute project first - this project code will be provided by your supervisor, research project or institution - noting that the first project you join will become your default; and (2) then join other projects, potentially including the following list of data projects {and then list things like ik11, cj50, etc etc}.
The reason for this suggestion is twofold. Firstly, I don't think we can recommend people to ask to join other peoples projects (like p66 or v45) and secondly the default project needs to be a compute project (I think, others can confirm ...)

From A:
PS. Further down it is noted:
`It is recommended that you change your default project on Gadi,`
I'm not sure about this, because if you choose the correct project first up, you don't need to do this. Maybe better to just say:
`If you need to change your default project on Gadi ...`

From M:
In https://access-hive.org.au/development_site/get_started/ the project list takes a lot of space and probably isn't necessary since the "run a model" sections list the necessary projects.
Instead say something like
"Each model configuration requires membership of certain projects for accessing data, tools and code. These are listed in the respective "Run a model" sections."
The full list might still be useful as a separate page that could be linked here but shouldn't be this prominent.

From A2:
Also keep maintainability in mind. Information duplicated is information that must be kept synchronised. So Martin’s suggestion is also a good one from this point of view. 

From P:
Also, on https://access-hive.org.au/development_site/get_started/ the projects in the list seem to be listed in no particular order. Would it be better to order alphabetically by Description or alphabetically by Project?

- [ ] To be reviewed by Andy, Romain, and Martin.

**Comment by atteggiani** [comment]
Decided to completely remove the project list
