### ISSUE TITLE
Why are Aerosol and Atm Chemistry components together?

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-Hive/access-hive.github.io#495]
## Description
Aerosol and Atmospheric Chemistry components are together in the component description. 
Why? 
They are not necessarily both present at the same time, and even if they were, they should be separated (like Land component and Biogeochemstry Land are)
|
https://access-hive.org.au/development_site/models/model_components/aerosols_atmospheric_chemistry/

## Why
To be consistent with the other component descriptions.

## Close Criteria
- [ ] Create two separate pages for Aerosol and Atm Chemistry components
- [ ] Update image (create two different images for each component)

**Comment by KAUR1984** [comment]
Hi @atteggiani ! Is this issue still relevant?
