### ISSUE TITLE
EXTERNAL REVIEW: COMMENTS

### ISSUE THREAD

**Issue by svenbuder** [ACCESS-Hive/access-hive.github.io#532]
To Fix:

- [x] In Getting started: add fifth bullet point “analysing model output” at top of page
- [x] Run ACCESS-OM and Run ACCESS-ESM, "First, is good practice ... " to "First, **it** is good practice ... " when creating new branch
- [x] In Model Evaluation -> Model Catalogues: Add information how to see all available models.
- [x] Add fourth panel to community resources that links to the forum
- [x] Whenever talking about PBS in "Run a Model", add link to NCI's PBS directive help (https://opus.nci.org.au/display/Help/PBS+Directives+Explained)
- [x] Whenever talking about PBS in "Model Evaluation", add link to NCI's PBS directive help (https://opus.nci.org.au/display/Help/PBS+Directives+Explained)
- [ ] Add icon to notify "Call to actions / infos" in the website (e.g. "To join a project .....", "To create an account ....")
- [x] Change wording on ACCESS-CM2 in model configurations "ACCESS-CM2 is a contribution to the CMIP6 program ..."  
- [x] Change wording on ACCESS-ESM in model configurations "ACCESS-ESM is a contribution to the CMIP6 program ..."
- [x] On "Getting Started" think about when it is "NCI Project" vs. "NCI Projects for Code and Managed Data Collections" + add explanation what an "NCI Project" is. Rephrase the "NCI is hosting a large amount of data" to separate Data Collections.
- [x] Add more explanation on "Observational Data" what all of the management etc. means. Include: https://opus.nci.org.au/display/Help/Data+Catalogue+User+Guide

**Comment by KAUR1984** [comment]
External review SharePoint link for feedback received through emails - https://anu365.sharepoint.com/:w:/r/sites/ACCESS-NRI/_layouts/15/Doc.aspx?sourcedoc=%7B4FF992C8-C88C-4A69-BF0A-B721632F8D62%7D&file=Ext_HiveReview_feedback.docx&action=default&mobileredirect=true

Also pinned at the top of the hive docs channel.

**Comment by atteggiani** [comment]
Wrote a separate issue for 'Add icon to notify "Call to actions / infos" in the website (e.g. "To join a project .....", "To create an account ....")' to be done after the release.
