### ISSUE TITLE
EVENTS: Have the Hive events page link to the main ACCESS-NRI events page

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#537]
## Description
On the community resources landing page, have a `events` card which links straight to the main ACCESS-NRI website. 

## Why
To avoid duplication of events page on both hive and the main website.

## Close Criteria
- [x] Restructure the community resources landing page to link to the main events page on the ACCESS-NRI website.

**Comment by atteggiani** [comment]
I took care of this within #532 
Closing @KAUR1984
