### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by HoWol76** [ACCESS-Hive/access-hive.github.io#575]
https://github.com/ACCESS-Hive/access-hive.github.io/blob/b74bc8bacbad6563470227834116ad5fcc8a6daa/mkdocs.yml#L157C14-L157C14

Probably too late now, but 'Overview' is misspelled. This is passed on to the `<title>` tag in the Workshop overview web page.

**Comment by KAUR1984** [comment]
Thanks so much for flagging that @HoWol76! Noted as a `typo` on Hive.

**Comment by atteggiani** [comment]
Merged in #591
