### ISSUE TITLE
WORKSHOP 2023: Restructure the formatting of 2023 workshop section on the Hive

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#582]
## Description

Restructure the placement and design of the workshop 2023 content on the Hive. An ideal restructuring should be flexible in terms of adding any future events.  

## Why

For enhancing the clarity of different sections across the Hive website. 

## Close Criteria

- [ ] Decide within the core team about the restructuring of the workshop 2023 content on the Hive.

**Comment by atteggiani** [comment]
Fixed in #592
