### ISSUE TITLE
DEPLOYMENT ERROR: Fix the syntax error in the workflow file for github actions

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#595]
## Description

The `build_preview.yml` file is returning a compile time error as follows: 

`The workflow is not valid. .github/workflows/build_preview.yml (Line: 17, Col: 9): Unexpected symbol: '"closed"'. Located at position 24 within expression: github.event.action != "closed"`.

![Screenshot 2023-10-30 at 12 44 55 pm](https://github.com/ACCESS-Hive/access-hive.github.io/assets/42607679/1bad0def-179a-4a95-bcc7-d9e5491b48cf)

## Why

For successful pr-preview deployments for new PRs.

## Close Criteria

- [ ] Resolve this github actions error.

**Comment by atteggiani** [comment]
Fixed with #605
