### ISSUE TITLE
GH-PAGES: Protect the `gh-pages` branch, similar to the main branch

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-Hive/access-hive.github.io#607]
## Description
Currently, the `gh-pages` branch is unprotected and anyone without restrictions could modify the deployment of the access-hive website. Implement the branch protections rule for the `gh-pages`.

## Why
For increased security of the branch and deployment. 

## Close Criteria
- [ ] Make `gh-pages` branch read-only.

**Comment by atteggiani** [comment]
`gh-pages` deleted, as now the deployment happens through GitHub actions, and the artifact gets created directly from the relevant branches.
