### ISSUE TITLE
Run ACCESS-ESM instructions - needs updating?

### ISSUE THREAD

**Issue by rml599gh** [ACCESS-Hive/access-hive.github.io#632]
## Description
The instructions for running ACCESS-ESM: https://access-hive.org.au/models/run-a-model/run-access-esm/#model-specific-prerequisites tell people to clone this github repository
git clone https://github.com/coecms/esm-pre-industrial.git

However, if you look at that repository, it says
"NOTE: Please don't use this any more. Use https://github.com/coecms/access-esm instead"

It assume it would be best to update the instructions to be consistent with the repository message.

## Why
Novice users like me get confused otherwise!

## Close Criteria
Consistent instructions

**Comment by atteggiani** [comment]
Addressed in #637
