### ISSUE TITLE
Teams structure

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#65]
Currently I have created a simple teams hierarchy
```mermaid
graph TD
A(Reviewers: triage) --> B(Editors: write) --> C(Maintainers: maintain)
```

Currently there is no "Members" group, just replying on people issuing PRs to become collaborators or just add people individually as members.

**Comment by ccarouge** [comment]
What is the difference between a "member" and a "collaborator" in terms of permissions etc.

**Comment by KAUR1984** [comment]
Closing as an old issue
