### ISSUE TITLE
Review Hub headers

### ISSUE THREAD

**Issue by kdruken** [ACCESS-Hive/access-hive.github.io#68]
Review headers for each side of site. Consider other logos and trying to rework how the name appears (can we limit the number of hyphens?)

**Comment by rbeucher** [comment]
@ccarouge I Think you have done that right?

**Comment by ccarouge** [comment]
Actually, I didn't look at logos. I've only changed the names for reducing the number of hyphens. @rbeucher do you still prefer to use the whole ACCESS-NRI logo?

**Comment by rbeucher** [comment]
I had a look last week. The colors make it difficult. Maybe later?

**Comment by rbeucher** [comment]
One thing I'm wondering about is the placement of the forum link.
In discourse I can only put the link to the HIVE in the top right corner. 
The link to the Forum on the Hive should also be in the top right corner...
What do you think?

Should I also keep it in the navigation?

@aidanheerdegen @kdruken @ccarouge

**Comment by ccarouge** [comment]
Top right would be good. Do you think as a last tab or something else?

I like the button in the navigation, I think I'd vote to keep it but not a strong feeling either way.

**Comment by aidanheerdegen** [comment]
There are plugins like [Versatile Banner](https://meta.discourse.org/t/versatile-banner/109133), but that isn't installed in the hosted version, so not sure why I suggested it :)

Just a small note, but when you're on the Forum and click on the ACCESS-Hive link, it opens a new window, but vice-versa and it does not.

I am not sure about the Forum link in the tabs. I like the idea, but all the other tabs are navigation within the site, but that takes you to a different site, but with a similar coloured header, so maybe a bit confusing?

**Comment by rbeucher** [comment]
I tried Versatile Banner. Not great

That's the all point I would like them to be integrated, not 2 different sites.

**Comment by aidanheerdegen** [comment]
Sounds nice, but I think probably too difficult right now with the mix we've chosen to use.

**Comment by rbeucher** [comment]
I think it works quite well actually

**Comment by aidanheerdegen** [comment]
The ask the community in the soft-launch if they like it and it makes sense to them. I'm not bothered if they're not.

**Comment by ccarouge** [comment]
@rbeucher @aidanheerdegen I'm guessing we need to review the colour theme for the forum as well now?

**Comment by rbeucher** [comment]
Done already.

**Comment by rbeucher** [comment]
Well maybe not the blue

**Comment by rbeucher** [comment]
I have changed it. Could be tweaked a bit more maybe?

**Comment by aidanheerdegen** [comment]
Looks good to me.
