### ISSUE TITLE
Soft launch!

### ISSUE THREAD

**Issue by kdruken** [ACCESS-Hive/access-hive.github.io#72]
- [ ] site review by @kdruken 
- [ ] prepare communication to reviewers to explain what we expect from them

**Comment by ccarouge** [comment]
@kdruken We are ready for a site review before the soft launch: https://access-hub.github.io/ACCESS-Hub/ 

@rbeucher just tagging you so you know I've asked Kelsey.

**Comment by ccarouge** [comment]
I'm starting [a doc](https://anu365.sharepoint.com/:w:/r/sites/ACCESS-NRI/Shared%20Documents/Release%20Management/[ACCESSHub_softlaunch_message](https://anu365.sharepoint.com/:w:/r/sites/ACCESS-NRI/Shared%20Documents/Release%20Management/ACCESSHub_softlaunch_message.docx?d=w408687358d094c76af9002b88e19bfd6&csf=1&web=1&e=8WdLab).docx?d=w408687358d094c76af9002b88e19bfd6&csf=1&web=1&e=8WdLab) to prepare the comm. to the reviewers for the soft launch.

**Comment by kdruken** [comment]
@ccarouge @rbeucher some feedback on text/items under each section for consideration (many or some of which might be things to consider before full launch):

- Could we combine the 2 tabs ‘ACCESS Hive’ and ‘About’ and just call it ‘About’? 
    - Use a subsection to put the info from the about tab there? 
    - And what did we want to put here - perhaps it’s a quick statement that directs viewers to the main website and the info on what to join (later when ready)?
        - Suggest just quick sentence or two directing to this link: https://www.access-nri.org.au/about/ (so we don’t have to support duplicate information)
        - Similarly for ‘contact info’, perhaps just direct here: https://www.access-nri.org.au/contact/ 
    - How to contribute linked page: 
        - It seems a bit dense… could we have a high-level summary of ways to contribute (i.e., like in the email draft)? Then for the corresponding way to contribute option, direct to this detailed guide?
        - Abstract of this page, I initially thought it was part of the site template — maybe it’d be helpful to add some text about ACCESS Hive so it’s more clear?
        - The images later down on page are now outdated - will need to be updated… will the screenshots here become an overhead to maintain?
    - Should we have an acknowledgement of country on that first splash screen? 
    - Along these lines what about a code of conduct or ethics statement? 
- Configurations
    - Review ordering of the configurations 
    - Maybe for full launch - put the ‘in development’ information/message into a box/message format? (Similar to the RSE example?) Might help highlight in a visual way things under development/coming soon
    - I’d maybe remove the last line ‘currently, …’ unless we want to link off somewhere to this information.
- Model components
    - Review ordering of how the components are listed
    - Put icons in same order to be consistent with the subsection list ordering
- Model Evaluation & Data
    - Define ‘MED’ acronym at start of description if it’ll be used
    - Though again, I’d consider keeping it general as ‘ACCESS-NRI will offer’ as it might be cleaner (mainly because we don’t have a clear public description of our org though I also think it helps keep it broad and inclusive for the community and other teams)
        - If going with this approach, the line ‘MED Team will offer:” could be rephrased to something ‘coming soon’ etc.
    - Under the ‘MED team will offer’ section, think we should rephrase a few of the dot points… need to have quick think and will add some suggestions (it’s mainly to avoid confusion or the grey area between what we can access or what is information we provide about access)
- Documentation and training
    - Suggest simplifying messaging here to just say ‘ACCESS-NRI’ instead of specific teams — again same reasons as above. 
    - Would add a box below like the RSE page to ask if you have info to contribute
    - ‘Training resources from partners’ - would suggest putting this into it’s own subsection and call it ‘Additional resources’ or something to that effect. Think the separate tab could be useful as we expand our info, provides an easy visual separate of what we offer/support vs related community resources
        - Under this section where ‘NCI Gadi’ is mentioned —> I’d suggest writing out National Computational Infrastructure (NCI) in full since it’s first time on the page being shown and link text to NCI’s website
    - ‘Technical trainings’ —> would ‘How-to guides’ be more helpful for us (thinking of content into the future and sometimes the definition of ‘technical’ is a grey area)
    - Policies - change to “Procedures and Practices” to be consistent with the repo name used
        - Also, when you click on the ‘procedures and practices’ link under the ‘policies’ tab, is this the expected action? Should it display a list or direct you to the repo? 
- Working groups
    - Add info message about what is coming
    - Question on whether we should remove the example working groups for now until they are confirmed? 
    - If they are listed as placeholders, review the ordering of how they appear
- Events - open questions, is this where we want to maintain this information? Since we don’t have anything yet on main website I think we should keep here for now and later confirm what site is best to host this info.
    - What about past events? Should we record these?
    - For ease of navigating, I might suggest one list for both workshops and conferences and then maybe a tab for past events?
    - We haven’t included anything around the level of support we provide or where to go for support. Need to decide position on this (and what to include) before full launch.

**Comment by ccarouge** [comment]
Closing this as I think we addressed most issues and have opened issues for what is left to address. Or things have become outdated.
